### ISSUE TITLE
pom editor: property content not shown

### ISSUE THREAD

**Issue by ca-stefan-cordes** [eclipse-m2e/m2e-core#492] opened 2022-01-13 07:49 UTC
When hover mouse over a ${} property the previous editor showed the value of that property and the definition source.

Example: <version>${db2jcc.version}</version>

New pom editor shows: nothing.

![image](https://user-images.githubusercontent.com/50696194/149287666-96e2efb0-60d3-4fef-9f5f-da9524b6d393.png)

Ref https://github.com/eclipse-m2e/m2e-core/issues/458#issuecomment-1006677185

**Comment by mickaelistria** [comment] 2022-01-13 09:28
This does work for me
![Screenshot from 2022-01-13 10-27-13](https://user-images.githubusercontent.com/469058/149302881-1b980970-ab42-4ef5-9635-db2423e611dc.png)
It could be that your issue is deeper and cascades to multiple symptoms.

**Comment by ca-stefan-cordes** [comment] 2022-01-13 10:04
Ok. Fine (probably new version).
What about "Jump to Location" ?

**Comment by ca-stefan-cordes** [comment] 2022-01-13 10:15
I checked with 1.18.4.20220112-1806 from https://download.eclipse.org/technology/m2e/snapshots/latest/
No popup coming up:
![image](https://user-images.githubusercontent.com/50696194/149310885-ab0f2da7-845e-41e0-a125-5cebe57cd647.png)
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.quaddy_services</groupId>
	<artifactId>escape-from-intranet</artifactId>
	<packaging>jar</packaging>
	<version>2019.5.22</version>
	<url>https://github.com/quaddy-services/escape-from-intranet</url>
	<properties>
		<version.maven-compiler-plugin>3.8.1</version.maven-compiler-plugin>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${version.maven-compiler-plugin}</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
				    <finalName>escape-from-intranet</finalName>
					<archive>
						<manifest>
							<mainClass>de.quaddy_services.proxy.EscapeProxy</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-eclipse-plugin</artifactId>
				<configuration>
					<downloadJavadocs>true</downloadJavadocs>
					<downloadSources>true</downloadSources>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

**Comment by ca-stefan-cordes** [comment] 2022-01-13 11:11
Looks like duplicate of https://github.com/eclipse-m2e/m2e-core/issues/437
(see https://github.com/eclipse/lemminx-maven/issues/238 )

**Comment by ca-stefan-cordes** [comment] 2022-01-13 13:16
Tried with "Language Server" ON but error log shows

```
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:73)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

and

```
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Builder must not be set
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:73)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
Caused by: java.lang.IllegalStateException: Builder must not be set
	at org.eclipse.mylyn.wikitext.parser.MarkupParser.parseToHtml(MarkupParser.java:114)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.lambda$0(LSPTextHover.java:99)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfoFuture(LSPTextHover.java:91)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:70)
	... 2 more
```

Pom file see: https://github.com/ca-stefan-cordes/m2e-core-test/blob/master/m2e-core-test-module1/pom.xml

**Comment by eliasbalasis** [comment] 2022-10-01 05:54
I am getting the same behavior on Eclipse 2022-09 , having first noticed on Eclipse 2022-03.

It feels like a Language Servers issue and I recall having to turn those off in the past due to various other issues.

However, turning Language Servers off didn't work either on Eclipse 2022-09.

We are stuck with Eclipse 2021-03 because of this, unable to upgrade.

I believe this relates to #839

**Comment by Kiiv** [comment] 2023-02-21 09:16
Mouse over is working for me on a property (showing a simple popup with the Value) but there is no "jump to location" option. The old popup was way more functional with the location of the property and the "Jump to location" link.

After few months, the new pom editor just seems a big regression for me :(

Versions :
Eclipse 2022-12
M2E - Maven Integration for Eclipse	2.1.2.20221130-2239	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

**Comment by Kiiv** [comment] 2023-02-21 09:36
Yup I could but I was asking here because @eliasbalasis seemed to say that "Jump to location" is working for him in Eclipse 2022-12 so I'm wondering why it is not for me :)

**Comment by mickaelistria** [comment] 2023-02-21 09:40
Maybe try latest snapshot which use latest lemminx-maven?
I'm closing this issue here because the value for the property is shown in the editor. Please open separate tickets for other issues. Smaller grain facilitates tracking and progress.

**Closed by mickaelistria** 2023-02-21 09:40 UTC
Labels: upstream-lemminx-maven

**Comment by ca-stefan-cordes** [comment] 2023-02-21 09:54
Thanks. Property value tooltip is shown now
![image](https://user-images.githubusercontent.com/50696194/220310531-ec6d564f-c018-465c-b0a2-5a896cee6497.png)

```
Eclipse.org - m2e	M2E Maven POM File Editor	2.0.2.20221115-1709	org.eclipse.m2e.editor
Eclipse.org - m2e	M2E Maven POM File Editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components)	2.0.1.20221120-2121	org.eclipse.m2e.editor.lemminx 
```
