### ISSUE TITLE
Non-resolvable parent POM for custom artifact

### ISSUE THREAD

**Issue by c-koell** [eclipse-m2e/m2e-core#287] opened 2021-07-21 09:34 UTC
Hi!

With the new Eclipse Release 2021.06 we get the following error after opening the pom.xml
```
Non-resolvable parent POM for AEICP:dvtdependenciespom:2021.10: AEICP:dvtparent:pom:60 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```
The missing POM is of course in our own maven repository (artifactory). Before the upgrade we havn't seen this error.
We have configured our maven repository (Artifactory) in the local settings.xml

Is this a bug or must we define our own repository in a other way with the new Plugin Version ?

**Comment by mickaelistria** [comment] 2021-07-21 10:48
Which version of m2e are you using? Can you please make sure latest one (1.18.1) is used?

**Comment by c-koell** [comment] 2021-07-21 12:14
I have checked (updated) the version and we use the latest one (1.18.1) now but we see the same error..

**Comment by mmalmeida** [comment] 2021-07-24 21:08
Same thing happening to me

**Comment by c-koell** [comment] 2021-07-29 09:27
Is the URL https://repo.maven.apache.org/maven2 anywhere hardcoded ?

**Comment by bolbat** [comment] 2021-07-30 15:28
The same problem on our projects
Error message: Non-resolvable parent POM for ......: Could not find artifact ......

Reproducible with m2e 1.18.0 and 1.18.1 on Eclipse (Version: 2021-06 (4.20.0) Build id: 20210612-2011)

**Comment by TomBenjamins** [comment] 2021-08-17 16:09
Same for my projects, running eclipse 21-06 with     
m2e - Maven Integration for Eclipse (includes Incubating components)	1.18.0.20210603-1206,
it started occurring after being forced to update the POM Editor using LemMinX language server (includes Incubating components)	1.17.2.20210411-0929

If i manually add the custom repo url  in the poms, it works again, but this should not be necessary, as the repo is already defined in my settings.xml.

If i revert to the previous installation without POM Editor using LemMinX language server (includes Incubating components)	1.17.2.20210411-0929 it works again.

**Comment by mickaelistria** [comment] 2021-08-17 16:14
I've retitled the issue to better capture the cause. If the issue you're facing seems different (eg no settings.xml involved), please open a separate ticket.

**Comment by mickaelistria** [comment] 2021-08-30 13:52
I think it's a symptom of https://github.com/eclipse/lemminx-maven/issues/221 ; I hope to send some good news about it in the next hour or so ;)

**Comment by mickaelistria** [comment] 2021-08-30 15:31
m2e now uses a version of lemminx-maven which includes the potential fix. Please install latest snapshots from https://download.eclipse.org/technology/m2e/snapshots/latest/ and report whether this works better for you.

**Comment by bolbat** [comment] 2021-08-30 15:42
Plugin updated to latest snapshot
![Screenshot 2021-08-30 at 18 41 18](https://user-images.githubusercontent.com/323609/131366080-95225938-9584-4092-aca3-ca5114fe6736.png)

But problem still exists
![Screenshot 2021-08-30 at 18 41 40](https://user-images.githubusercontent.com/323609/131366116-3aad7a9b-70dc-41f0-96d7-7b16fc6738e0.png)

**Comment by mickaelistria** [comment] 2021-08-30 16:54
Do you override the local repo or anything else non-standard that would prevent lemminx-maven from fetching the jar? Maybe some proxy or network settings?

**Comment by bolbat** [comment] 2021-08-30 18:28
> Do you override the local repo or anything else non-standard that would prevent lemminx-maven from fetching the jar? Maybe some proxy or network settings?

Configuration in .m2/settings.xml has company maven repository (Nexus based), last time changed years ago and works perfectly with any previous Eclipse version, problem only with m2e 1.18.x, with 1.17.x all works good

Configuration (.m2/settings.xml) looks like this (just removed URLs and credentials)
```
<settings xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://maven.apache.org/POM/4.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <localRepository />
        <interactiveMode />
        <usePluginRegistry />
        <offline />
        <pluginGroups />
        <servers>
                <server>
                        <id>company-repo-id</id>
                        <username>company-user-name</username>
                        <password>company-user-pass</password>
                </server>
        </servers>
        <mirrors>
                <mirror>
                        <id>company-repo-id</id>
                        <url>https://company-repo-url</url>
                        <mirrorOf>*</mirrorOf>
                </mirror>
        </mirrors>
        <proxies />
        <profiles>
                <profile>
                        <activation>
                                <activeByDefault>true</activeByDefault>
                        </activation>
                        <repositories>
                                <repository>
                                        <id>company-repo-id</id>
                                        <url>https://company-repo-url</url>
                                        <releases>
                                                <enabled>true</enabled>
                                        </releases>
                                        <snapshots>
                                                <enabled>true</enabled>
                                        </snapshots>
                                </repository>
                        </repositories>
                </profile>
        </profiles>
        <activeProfiles />
</settings>
```

All dependent projects deployed locally and published to repository, also opened in Eclipse, everything builds in Eclipse and from console
Problem just with pom editor

**Comment by bolbat** [comment] 2021-08-31 11:36
And also when i'm trying to open parent pom from editor by clicking (by cmd+click) on the parent section in current pom (on which i see error) - all works just fine, parent pom opening in separate window

**Comment by mickaelistria** [comment] 2021-08-31 14:03
The issue comes from LemMinX-Maven; and I think several of the issues reported here should now be resolved but your case is still failing (probably lemminx-maven is not handling well either the server part or the mirrors). It would be great if you could help in troubleshooting that in LemMinX-Mavne directly, by first reporting this issue to lemminx-maven and then trying to reduce this to a minimal portable reproducer.

**Comment by bolbat** [comment] 2021-09-01 10:48
@mickaelistria reproducing is easy

Checkout and open the next project in Eclipse as maven project
https://code.solutionary.tech/projects/OS/repos/base-parent/browse

This is 'parent' project with base configuration for our company projects, it was based on org.sonatype.oss:oss-parent, wich is accessible from maven central repository

Any configuration .m2/settings.xml can be disabled, i was renamed it to .m2/settings.xml.bak and rebuild project in Eclipse

And i see the next warnings:
![Screenshot 2021-09-01 at 13 39 02](https://user-images.githubusercontent.com/323609/131658417-583f453d-9a3b-4e1c-8e3f-cd4b06edb4c3.png)

This warnings is the same symptoms of the editor problem as with "not resolving parent pom" error

Example for other internal project wich is based on our parent pom - you can see also the same warnings
![Screenshot 2021-09-01 at 13 41 30](https://user-images.githubusercontent.com/323609/131658543-2e2fb08f-0939-45ab-8aa5-43e3bfc8d266.png)

With m2e v1.17.x everything works fine as expected without any errors and warnings

**Comment by bolbat** [comment] 2021-09-01 11:09
My previous comment edited multiple times, now it's final

**Comment by fbricon** [comment] 2021-09-01 11:30
Until lemminx-maven is fixed, you can disable `XML Language Server` in the `Language Servers` preferences
<img width="1049" alt="Screenshot 2021-09-01 at 13 27 36" src="https://user-images.githubusercontent.com/148698/131663745-e25cc24a-24c1-41d4-bad3-321e28c9312d.png">

**Comment by bolbat** [comment] 2021-09-01 11:32
> Until lemminx-maven is fixed, you can disable `XML Language Server` in the `Language Servers` preferences

Thx, this was helpful

**Comment by mickaelistria** [comment] 2021-09-02 07:31
@bolbat I tried to reproduce with the steps described in https://github.com/eclipse-m2e/m2e-core/issues/287#issuecomment-910164083 and couldn't see the "non-resolvable parent pom". In "Help > Installation Details", can you please verify that you have   "POM Editor using LemMinX language server (includes Incubating components)	1.18.2.20210830-1339	org.eclipse.m2e.lemminx.feature.feature.group" with the same version?

> This [Plugin could not be resolved] warnings is the same symptoms of the editor problem as with "not resolving parent pom" error

I don't think they're related. They seem like a distinct problem/fix.

**Comment by bolbat** [comment] 2021-09-02 08:56
> @bolbat I tried to reproduce with the steps described in [#287 (comment)](https://github.com/eclipse-m2e/m2e-core/issues/287#issuecomment-910164083) and couldn't see the "non-resolvable parent pom". In "Help > Installation Details", can you please verify that you have "POM Editor using LemMinX language server (includes Incubating components) 1.18.2.20210830-1339 org.eclipse.m2e.lemminx.feature.feature.group" with the same version?

Installed versions
![Screenshot 2021-09-02 at 11 30 55](https://user-images.githubusercontent.com/323609/131812964-dc93a98e-920a-4a0c-af4d-dcebdedad2f2.png)

Today i've got updates
![Screenshot 2021-09-02 at 11 47 15](https://user-images.githubusercontent.com/323609/131813259-4da81908-0ce1-4614-8e87-db309ad676ae.png)

Currently installed versions (after update)
![Screenshot 2021-09-02 at 11 49 33](https://user-images.githubusercontent.com/323609/131813550-aeef6166-6ed7-45c6-85e8-cd25dc4cfbdf.png)

Checked with enabled "XML Language server" after update - situation is the same
![Screenshot 2021-09-02 at 11 51 57](https://user-images.githubusercontent.com/323609/131813910-d90170d9-26e3-4802-a9b3-43ab2cdc0123.png)

> I don't think they're related. They seem like a distinct problem/fix.

I think they are related because with m2e (+ related plugins) on the v1.17.x no any error/warning in pom editor


P.S. If this can be helpful - we can make an online call/conversation with screen sharing and you can check everything on my local environment

**Comment by mickaelistria** [comment] 2021-09-02 09:12
I can now reproduce the issue, but it requires that the "child" pom is open before the parent one; once parent was open, any change on the child will make the warning disappear (because parent is now known to LemMinX-Maven).
This issue may be in m2e or LemMinX-Maven, I'm investigating.

The plugin resolution issue is independent of parent resolution and can be reproduce with a basic pom in LemMinX-Maven test suite, see https://github.com/eclipse/lemminx-maven/pull/224

**Comment by eliasbalasis** [comment] 2021-09-02 13:33
If it helps you, under #152 I always open the parent project first and the problem is always reproducible.

**Comment by mickaelistria** [comment] 2021-09-02 13:38
> unless something has improved since last time I tried this (Apr. 8 2021)

111 commits were merged since then. Please give a try to latest snapshots.

**Comment by mickaelistria** [comment] 2021-09-02 14:00
I think the root cause is in LemMinX-Maven: https://github.com/eclipse/lemminx/issues/1110 . Because of it, the underlying language server is not informed about other local projects.

**Comment by mickaelistria** [comment] 2021-11-09 21:24
Patch was merged on master that should fix it; this will be available in https://download.eclipse.org/technology/m2e/snapshots/latest/ within a dozen of minutes.

**Closed by mickaelistria** 2021-11-09 21:24 UTC
