### ISSUE TITLE
Comment/Uncomment (ctrl-shift-c) doesn't work.

### ISSUE THREAD

**Issue by gnl42** [eclipse-m2e/m2e-core#1114] opened 2022-12-03 04:10 UTC
POM Editor 2.0.2.20221130-2134

**Comment by mickaelistria** [comment] 2022-12-03 10:04
Duplicate of #856 and some others.
m2e is not involved in that part. Please install latest release of [Eclipse TM4E ](https://github.com/eclipse/tm4e) which has fixed it.

**Closed by mickaelistria** 2022-12-03 10:04 UTC

**Comment by gnl42** [comment] 2022-12-04 03:31
I would still say it's a bug in m2e  since I've never heard about TM4E, nor has there been any indication that it is required to make the POM editor complete.

From the TM4E website: `TM4E is usually installed together with its consumers, so end-user should usually not need to directly install it.`
so at the very least m2e should have a reference to TM4E and automatically include it in the installation
