### ISSUE TITLE
Opening pom from jar fails with ClassCastException

### ISSUE THREAD

**Issue by ca-stefan-cordes** [eclipse-m2e/m2e-core#526] opened 2022-01-27 09:08 UTC
Opening a pom.xml from the
/META-INF/maven/com.retail-sc.rdm/rdm-ejb/pom.xml
in "Maven Dependencies" jar file fails with
```
java.lang.ClassCastException: class org.eclipse.jface.text.Document cannot be cast to class org.eclipse.wst.sse.core.internal.provisional.text.IStructuredDocument (org.eclipse.jface.text.Document is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @240a9052; org.eclipse.wst.sse.core.internal.provisional.text.IStructuredDocument is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7dcc909c)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.setModel(MavenPomEditor.java:370)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.addPages(MavenPomEditor.java:331)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:143)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
```
![image](https://user-images.githubusercontent.com/50696194/151327037-b5139533-3f64-45f5-8f99-7379971d7337.png)

Version: 2021-12 (4.22.0)
Build id: 20211202-1639

org.eclipse.m2e.lemminx.feature.feature.group 1.18.4.20220112-1806

![image](https://user-images.githubusercontent.com/50696194/151327401-05cb3e71-c8f0-4272-bbbb-4df974a5c6bd.png)

**Comment by mickaelistria** [comment] 2022-01-27 09:10
Duplicate of #501

**Comment by ca-stefan-cordes** [comment] 2022-01-27 09:41
Ok. Thanks. My fault. I searched for ClassCastException in "open" issues only.

But I cannot confirm it is working.

after updating to org.eclipse.m2e.lemminx.feature.feature.group 1.18.4.20220124-1132 pom.xml still fails with
```
java.lang.ClassCastException: class org.eclipse.jface.text.Document cannot be cast to class org.eclipse.wst.sse.core.internal.provisional.text.IStructuredDocument (org.eclipse.jface.text.Document is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @33ef701e; org.eclipse.wst.sse.core.internal.provisional.text.IStructuredDocument is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7626e9ff)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.setModel(MavenPomEditor.java:371)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.addPages(MavenPomEditor.java:331)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:143)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
```

**Comment by mickaelistria** [comment] 2022-01-27 10:47
OK, I closed too fast because the stack was really similar, but I tried it and confirm that I can reproduce the issue on my environment as well, with latest snapshots.

**Closed** 2022-01-31 15:03 UTC
