### ISSUE TITLE
Lemminx POM editor does not seem to support "Open selection"

### ISSUE THREAD

**Issue by dnb-erik-brangs** [eclipse-m2e/m2e-core#739] opened 2022-05-31 12:21 UTC
The legacy POM editor supports "Open selection" (bound to F3 in my installation) when right clicking on POM elements like the tags inside of ``<parent>`` or inside of ``<dependencies>``. This allows navigation to the parent POMs and the POMs of the dependencies. I think this feature is very useful.

The Lemminx editor in Eclipse 2022-03 does not seem to support this feature. Please add it.

**Comment by mickaelistria** [comment] 2022-05-31 12:23
Does Ctrl+Click work?

**Comment by dnb-erik-brangs** [comment] 2022-05-31 12:33
Ctrl+Click does not work in the Lemminx editor. I can only Ctrl+Click on the maven elements itself (e.g. ``<parent>`` or ``<dependency>``) and only have "Open declaration" at that point. Selecting "Open declaration" opens the definitions of the elements in the Maven XSD.

**Comment by mickaelistria** [comment] 2022-05-31 12:35
This feature is available, but seems to be failing in your case. Can you please try on a fresh workspace with a very basic pom file, and ensuring latest releases of Wild Web Developer and m2e are installed?

**Comment by dnb-erik-brangs** [comment] 2022-05-31 14:36
[.log](https://github.com/eclipse-m2e/m2e-core/files/8806082/default.log)
[org.eclipse.wildwebdeveloper.xml.log](https://github.com/eclipse-m2e/m2e-core/files/8806083/org.eclipse.wildwebdeveloper.xml.log)

I'm on Windows. I've tried ``tasklist /v | findstr /c:"lemminx"`` and didn't find anything. Should I try something else?

**Comment by mickaelistria** [comment] 2022-05-31 14:45
No need for further investigation, the cause is visible in .log file
```
java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.3.20220227-1319/jars/
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URL.toURI(URL.java:1018)
	at org.eclipse.m2e.editor.lemminx.MavenRuntimeClasspathProvider.addJarsFromBundle(MavenRuntimeClasspathProvider.java:81)
	at org.eclipse.m2e.editor.lemminx.MavenRuntimeClasspathProvider.get(MavenRuntimeClasspathProvider.java:66)
	at org.eclipse.m2e.editor.lemminx.MavenRuntimeClasspathProvider.get(MavenRuntimeClasspathProvider.java:1)
```
It's a duplicate of #621 that is fixed in current snapshots ( https://download.eclipse.org/technology/m2e/snapshots/latest/ ) and next m2e release.

**Closed by mickaelistria** 2022-05-31 14:45 UTC

**Comment by dnb-erik-brangs** [comment] 2022-05-31 14:52
I can't verify that because the snapshot isn't installable in my Eclipse. Do I have to wait for 2022-06 for a fix?

**Comment by mickaelistria** [comment] 2022-05-31 15:20
> I can't verify that because the snapshot isn't installable in my Eclipse. Do I have to wait for 2022-06 for a fix?

What's the error when trying to install it?

**Comment by dnb-erik-brangs** [comment] 2022-05-31 15:25
There's a dependency conflict with JBoss Tools and m2e WTP. Eclipse can't find a solution. The "solutions" offered by Eclipse include uninstalling JBoss Tools and m2e WTP to install the m2e snapshot.
