### ISSUE TITLE
m2e plugin "looses" resources after changes pom.xml - using 2.4.100.20230827-1557

### ISSUE THREAD

**Issue by lihomev5** [eclipse-m2e/m2e-core#1585] opened 2023-10-25 08:02 UTC
I am experiencing a problem with the `m2e` plugin in `Eclipse`. After making changes to my `pom.xml`, specifically `adding` or `removing` a `dependency`, the project's `src/main/resources` and `src/test/resources` files are not automatically copied to the `target` directory. However, when I `right-click` on the project and choose `"Maven" > "Update Project..."` the resources are properly copied to the target directory. This seems to be an issue with the automatic resource copying mechanism of `m2e`.

### Version Information:

Eclipse Version: [2023-09 (4.29.0), Build id: 20230907-1323]
m2e Plugin Version: [Maven Integration for Eclipse  2.4.100.20230827-1557]
Maven Version: [3.9.4]
Operating System: [MacOS Monterey 12.7]

### Steps to Reproduce:

Open an Eclipse Maven project.
Edit the `pom.xml` by `adding or removing` a `dependency`.
Observe that the `src/main/resources` and `src/test/resources` files are not copied to the `target` directory.
Right-click on the project, choose `"Maven" > "Update Project..."` and observe that the resources are now copied to the target directory.
Expected Behavior:
I expect that after modifying the pom.xml, the resources in `src/main/resources` and `src/test/resources` should be automatically copied to the `target` directory without the need to manually trigger "Update Project."

### Actual Behavior:
The resources in `src/main/resources` and `src/test/resources` are not copied to the target directory automatically after modifying the pom.xml. Manual intervention by right-clicking on the project and updating it is required.

### Additional Information:

There are no error messages or warnings in the Eclipse IDE.
I have verified that the Maven build process is configured correctly in the pom.xml.
This issue is affecting my workflow and productivity as it requires manual intervention each time I make a change to the pom.xml.
Possible Solutions:
I am not sure about the exact cause of this issue, but it seems like there might be an issue with the m2e plugin's automatic resource copying mechanism. It might be worth investigating the plugin's behavior in response to changes in the pom.xml.

### Notes:
I have tested this issue on different projects and the problem persists.

**Comment by laeubi** [comment] 2023-10-25 08:23
> This seems to be an issue with the automatic resource copying mechanism of m2e.

m2e does not copy anything, maven-resource-plugin does:
- https://github.com/apache/maven-filtering/pull/77

**Comment by tarioch** [comment] 2023-10-25 13:10
I think this is a duplicate of #1511

**Comment by tarioch** [comment] 2023-10-25 13:13
Right now the workaround we're having is to have a launcher which will touch all resource files. So basically after building, we'll then need to launch this and as now eclipse detects the files as modified, they will get copied over into the resources again.

**Comment by lihomev5** [comment] 2023-10-30 03:54
> > This seems to be an issue with the automatic resource copying mechanism of m2e.
> 
> m2e does not copy anything, maven-resource-plugin does:
> 
> * [[MSHARED-1285] use an up-to-date scanner instead the newscanner apache/maven-filtering#77](https://github.com/apache/maven-filtering/pull/77)

I've downgraded the version to 2.1.2, and it is as normal as [tarioch](https://github.com/tarioch) said.
just uninstall it, then use this url: "Eclipse IDE integration for Maven - https://download.eclipse.org/technology/m2e/releases/2.1.2" to install it.
I am using eclipse 2023-09 (4.29.0)

**Comment by fmarot** [comment] 2023-11-21 08:22
my own workaround is to have a Maven launcher in Eclipse running "resources:resources" each time before launching my software. This is not ideal.

**Comment by HannesWell** [comment] 2023-12-10 13:35
> I think this is a duplicate of #1511

I think so as well. I'll close this as duplicate of #1511.
Please follow that issue for updates. The good news is that @laeubi's PR to fix this up-stream makes good progress (https://github.com/apache/maven-filtering/pull/77).

**Comment by HannesWell** [comment] 2023-12-10 13:36
Duplicate of #1511

**Closed by HannesWell** 2023-12-10 13:36 UTC
