### ISSUE TITLE
Archetype property-expansion is not performed and validationRegex is ignored

### ISSUE THREAD

**Issue by hd42** [eclipse-m2e/m2e-core#799] opened 2022-06-20 06:29 UTC
We have an archetype ([faktorips-maven-archetype](https://mvnrepository.com/artifact/org.faktorips/faktorips-maven-archetype), mostly works now thanks to #249) that uses parameter replacement to calculate the default value of a property, which works fine when executing the archetype on the command line, because the properties are evaluated one after the other. In Eclipse, the GAV-coordinates and all properties are displayed on one page, which is nice but breaks this inter-property dependency.

In our archetype-metadata.xml, we have 
```
    <requiredProperties>
        [...]
        <requiredProperty key="IPS-RuntimeIdPrefix">
            <defaultValue>${artifactId.concat(".")}</defaultValue>
            <validationRegex>[a-zA-Z](?:\.?[a-zA-Z\d])*\.</validationRegex>
        </requiredProperty>
        [...]
    </requiredProperties>
```
Unfortunately, the artifactId is not replaced here. I'm not sure what a nice solution would look like, because changing the value constantly might confuse the user. Maybe one could evaluate the replacement as as long as the field's value has not been manually edited (so that for example changes to the artifactId are reflected) and then keep whatever the user entered.

The validationRegex also seems not to be evaluated.

**Comment by laeubi** [comment] 2022-06-20 06:34
@hd42 thanks for reporting this, I think these are missing feature at the moment, I'll take a look at it.

**Comment by laeubi** [comment] 2022-06-20 15:54
Regexp are now checked.

For the properties expansion it is a bit more complex, as you said, the Archetype Generator assigns values step by step and evaluates the value using Velocity.

I see two options:

1. If there is an expression to evaluate we simply remove it from the wizard and let the user enter it on the commandline
2. we try to embed velocity (again) even though @HannesWell recently removed it to get a smaller footprint and try to emulate the way archetype works as much as possible

@hd42 any concerns for option 1? Given that we want to delegate as much as possible to the maven part it seems the logical choice here, while 2 of course would maybe much more "magic" / comfortable?

**Comment by hd42** [comment] 2022-06-20 19:05
@laeubi I don't think that option 2 can handle all options, so some variant of option 1 would probably be better. Either (a) silently remove any property containing an expression for its default value, so that it has to be entered on the command line, or (b) keep it and just remove the default value, maybe adding a comment, why there is no value and maybe even presenting the expression as a tooltip. 

I think option 1a is probably the best. 1b would allow an experienced user to enter all values in the UI table, but as we already have the console for any input needed by the groovy script, using it for any missing properties as well seems fitting.

**Comment by HannesWell** [comment] 2022-06-20 20:32
>     2. we try to embed velocity (again) even though @HannesWell recently removed it to get a smaller footprint and try to emulate the way archetype works as much as possible
> 
I'm currently not familiar enough with the topic to say what a good solution for the problem is, but if embedding more artifacts is necessary just remove the corresponding exclusion. As long as it is not `groovy-all` or `ivy` trying hard to avoid them is IMHO not necessary.

**Comment by laeubi** [comment] 2022-06-21 06:32
The fix for this should appear shortly in the snapshots.

This issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).

**Closed** 2022-06-22 08:48 UTC
Labels: Archetype Generation, sponsored
