### ISSUE TITLE
m2e catgalog wizard is not working when open catalog is clicked

### ISSUE THREAD

**Issue by jimmybirrias** [eclipse-m2e/m2e-core#179] opened 2021-04-26 16:46 UTC
Hello M2E team I am looking for some help regarding with the m2e catalogs with the m2e connectors install wizard, I am getting the following error when I click Window > Preference > Maven > Discovery > Open catalog I got this message in the wizard:

![image](https://user-images.githubusercontent.com/10710943/116119784-6aa4a100-a684-11eb-9a64-2ef0a950eb0e.png)
Also in the $workspace/.metadata/.log I am seeing this stack trace:
```
org.eclipse.core.runtime.CoreException: IO failure: cannot load discovery directory
        at org.eclipse.equinox.internal.p2.discovery.compatibility.RemoteBundleDiscoveryStrategy.performDiscovery(RemoteBundleDiscoveryStrategy.java:94)
        at org.eclipse.equinox.internal.p2.discovery.Catalog.performDiscovery(Catalog.java:85)
        at org.eclipse.m2e.internal.discovery.wizards.MavenCatalogViewer$2.run(MavenCatalogViewer.java:164)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: org.eclipse.equinox.internal.p2.discovery.compatibility.util.IOWithCauseException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
        at org.eclipse.equinox.internal.p2.discovery.compatibility.DirectoryParser.parse(DirectoryParser.java:43)
```
I have checked the catalog URL (http://download.eclipse.org/technology/m2e/discovery/directory-1.8.xml) and it is reachable:
![image](https://user-images.githubusercontent.com/10710943/116120297-01715d80-a685-11eb-92d5-7ab1ff943d00.png)

My question here is, is there a workaround for this issue?

**Comment by vrubezhny** [comment] 2021-04-28 11:02
@jimmybirrias Could you please specify what is  the version you're running on and tell if you are behind any proxy?
In case if it's possible, Could you please try to update to the latest version and try again? 

Thanks in advance

**Comment by jimmybirrias** [comment] 2021-04-28 18:54
Thanks for the response @vrubezhny, I am not running eclipse behind of any proxy or vpn

**Comment by vrubezhny** [comment] 2021-04-28 20:27
@jimmybirrias Thanks for the details.

Unfortunately, as I said, m2e is not supported against Java 8. So please use at least Java 11. 

HTH

**Comment by eliasbalasis** [comment] 2024-06-15 11:05
This is still failing on Eclipse 2024-06 running on Java 21 and either Windows 10 or 11

```
org.eclipse.equinox.p2.core.ProvisionException: An error occurred while downloading https://github.com/eclipse-m2e/m2e-discovery-catalog/releases/download/2.x/catalog-2.x.xml. The cache file <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\downloading\discovery554145892 could not be renamed to <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\discovery554145892.
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.updateCache(CacheManager.java:228)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.createCache(CacheManager.java:137)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.TransportUtil.readResource(TransportUtil.java:99)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.RemoteBundleDiscoveryStrategy.performDiscovery(RemoteBundleDiscoveryStrategy.java:84)
	at org.eclipse.equinox.internal.p2.discovery.Catalog.performDiscovery(Catalog.java:88)
	at org.eclipse.m2e.internal.discovery.wizards.MavenCatalogViewer.lambda$1(MavenCatalogViewer.java:158)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

The problem is not present in Eclipse 2023-12 though.

This is shooting on the foot everyone wanting to upgrade.

**Comment by christopherj89** [comment] 2024-07-01 09:17
> This is still failing on Eclipse 2024-06 running on Java 21 and either Windows 10 or 11
> 
> ```
> org.eclipse.equinox.p2.core.ProvisionException: An error occurred while downloading https://github.com/eclipse-m2e/m2e-discovery-catalog/releases/download/2.x/catalog-2.x.xml. The cache file <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\downloading\discovery554145892 could not be renamed to <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\discovery554145892.
> 	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.updateCache(CacheManager.java:228)
> 	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.createCache(CacheManager.java:137)
> 	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.TransportUtil.readResource(TransportUtil.java:99)
> 	at org.eclipse.equinox.internal.p2.discovery.compatibility.RemoteBundleDiscoveryStrategy.performDiscovery(RemoteBundleDiscoveryStrategy.java:84)
> 	at org.eclipse.equinox.internal.p2.discovery.Catalog.performDiscovery(Catalog.java:88)
> 	at org.eclipse.m2e.internal.discovery.wizards.MavenCatalogViewer.lambda$1(MavenCatalogViewer.java:158)
> 	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
> ```
> 
> The problem is not present in Eclipse 2023-12 though.
> 
> This is shooting on the foot people wanting to upgrade.

facing the same issue with eclipse 2024-06

**Comment by TB-HunBoka** [comment] 2024-07-15 21:53
I was facing the same issue. Problem is it could not move the file from the downloading folder to the cache folder. (No idea why)
If you see the "could not be renamed to" text in the error message then there is a workaround:
copy the files from the downloading folder to cache. You have to do that twice.
Here are the stepts:
1. click Window > Preference > Maven > Discovery > Open catalog
2. copy the file **discovery554145892** from <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\downloading\ to <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\ 
3. click Window > Preference > Maven > Discovery > Open catalog
4. copy the file **discovery-1503674835** from <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\downloading\ to <workspace>\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\ 
5. click Window > Preference > Maven > Discovery > Open catalog should work

**Comment by gloowa** [comment] 2024-08-02 20:22
I can confirm the problem with "cannot be renamed" still exists and above workaround works. 

The problem is in 

`org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.updateCache`

```if (result.isOK()) {
	if (cacheFile.exists())
		safeDelete(cacheFile);
		if (temp(tempFilFile.renameTo(cacheFile)) {
			(...)
```

`File.renameTo()` does not support changing file path, and it says so in the method javadoc.
`Files.move()` should be used instead.

I've opened https://github.com/eclipse-equinox/p2/issues/536 for this

**Comment by merks** [comment] 2024-08-03 13:39
This problem is caused by the issue reported against p2 which is now fixed:

https://github.com/eclipse-equinox/p2/issues/536

**Comment by HannesWell** [comment] 2024-08-04 07:07
Thank you @gloowa for the investigation and thank you Ed for the fix. 
Both is very welcome!

**Closed** 2024-08-04 07:07 UTC
Labels: usability
