### ISSUE TITLE
Pom.xml editor doesn't have all the features it previously did

### ISSUE THREAD

**Issue by pauldaustin** [eclipse-m2e/m2e-core#458] opened 2021-12-16 15:56 UTC
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2021-12 (4.22.0)
Build id: 20211202-1639
OS: macOS Monterey

Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature

All software updates have been applied.

After update to the version above the pom.xml is no longer working.

- The syntax highlighting is a different color (which make me think it's using the wrong editor component).
- The outline windows shows 'There is no active editor that provides an outline'
- Format source doesn't work
- Proposals for valid xml tags doesn't work

I can't roll back as previous versions of m2e had the repeated download sources bug

**Comment by mickaelistria** [comment] 2021-12-16 17:36
> The syntax highlighting is a different color (which make me think it's using the wrong editor component).

Not wrong, but different.

> The outline windows shows 'There is no active editor that provides an outline'
> Format source doesn't work
> Proposals for valid xml tags doesn't work

Can you please open 1 dedicated ticket for each one of those issues?

**Comment by paulaustin-automutatio** [comment] 2021-12-16 23:06
I've got a feeling that this might be an issue that my installed version (2021-09) was then upgraded to use some of the new features in eclipse 2021-12. Those caused the version to be bumped, but it may not have included all the features for 2021-12. I will try again when 2012-12 is available through homebrew.

**Comment by blacelle** [comment] 2021-12-17 21:19
I have a similar issue. I also thought of an issue upgrading a workspace, but I have the same issue with a fresh repo:

![image](https://user-images.githubusercontent.com/2117911/146609195-38a5a636-5d35-44db-abf0-5a8b89a6a927.png)

I used to be ablew to ctrl+whitespace to open the add-dependency helper, but now, I only get XML specific helpers.

**Comment by blacelle** [comment] 2021-12-17 21:23
Most of ctrl+click navigation is also gone. It seems to behave like if most mvn features is not available.

**Comment by blacelle** [comment] 2021-12-17 21:25
![image](https://user-images.githubusercontent.com/2117911/146609718-6040e805-d930-4a18-8a63-50729bbceb55.png)

**Comment by mickaelistria** [comment] 2021-12-17 22:04
@blacelle can you reproduce this issue with any pom file? What is the warning on the schemaLocation?

**Comment by blacelle** [comment] 2021-12-17 22:14
Unclear why, but after living a bit in this Eclipse, I see no more schema issue:

![image](https://user-images.githubusercontent.com/2117911/146614010-12d7099b-b990-4b2d-ad98-5be0c86b2b31.png)

I'm now offered to add dependency node. But it seems still naive XML autocompletion

**Comment by blacelle** [comment] 2021-12-19 17:33
> can you reproduce this issue with any pom file?

Yes

**Comment by rhoehener** [comment] 2021-12-20 09:25
I am also missing the Ctrl+Shift+C shortcut for toggling comments.

**Comment by ca-stefan-cordes** [comment] 2021-12-21 20:57
Another not working feature:
* Fill end tag:

Type "<version>1.0.0" and the < and / 
old editor: `<version>1.0.0</version>`
new editor: `<version>1.0.0</>`

![image](https://user-images.githubusercontent.com/50696194/146996271-e10e47d1-d5bf-409d-a41a-a59d0022d777.png)

For workaround: As "--All Available Sites--" may be slow when having many plugins here the direct link to the 
repo of "POM Editor (Legacy)":
Latest Eclipse Simultaneous Release - https://download.eclipse.org/releases/latest

**Comment by blacelle** [comment] 2021-12-21 22:03
Thanks @ca-stefan-cordes for the workaround.

Weirdly enough, this led to some previous transient issue appearing again: @mickaelistria , on schema issues, details regarding the missing schema is:

> schema_reference.4: Failed to read schema document 'bundleentry://260.fwk1486040578/xsd/maven-v4_0_0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

**Comment by bgaraude** [comment] 2021-12-22 09:25
I also experience the lack of some features on Windows 10 Enterprise:
Version: 2021-12 (4.22.0)
Build id: 20211202-1639

I noticed that when in the <configuration> tag of a plugin, the legacy editor gave completion for the plugin configuration properties.
The new editor only suggests <project> for any plugins.

CRTL+click navigation through artifacts is also gone, I miss it a lot.

However, I have no error/warnings on the schemaLocation, and:
* the completion for the pom elements works fine (except within the <configuration> tag of plugins)
* formatting the pom file is ok and 
* outline is different but ok
* syntax highlighting is different but ok

But I also ended up installing the legacy editor. I really miss the navigation, and plugin configuration proposals.

**Comment by harbulot** [comment] 2021-12-23 16:30
It looks like the new `pom.xml` editor also ignores some XML editor settings.

More specifically, it still uses tabs even if you've configured "*XML*" > "*XML Files*" > "*Editor*" with "*Indent using spaces*".

**Comment by nitind** [comment] 2021-12-23 17:03
That preference applies to the XML Editor, and XML editors based on it. It wouldn't apply to the revamped source page in the POM Editor.

**Comment by harbulot** [comment] 2021-12-23 17:20
@nitind That's fair enough. I must admit I didn't really follow the reasons for revamping/changing the POM XML editor (I'm sure there are good ones). It looks like a few of us are missing some features that used to be provided by the default XML Editor, yet I'm not sure what new features have been gained (at least from a user point of view).

**Comment by nitind** [comment] 2021-12-23 17:40
I'm not sure what features are missing from the XML Editor itself, but it would be good to log them as enhancement requests over in Bugzilla.

**Comment by barfoo4711** [comment] 2021-12-31 13:41
thank you very much for the workaround! The Missing ctrl+shift+c was driving me crazy. Would be nice to fix this soon :) Can I vote for this issue anywhere?

**Comment by mickaelistria** [comment] 2022-01-02 21:44
Comment issue is covered in #462

**Comment by davidmichaelkarr** [comment] 2022-01-03 18:26
The biggest problem I see is losing navigation to artifact poms.

Is the conclusion so far that the only available fix is to install the legacy pom editor?

**Comment by mickaelistria** [comment] 2022-01-03 19:01
Navigation is supposed to work, however I've also experimented troubles with it lately. I am not aware of another workaround and I hope someone (maybe me) will be able to look at this issue soon.

**Comment by CarlosMOGoncalves** [comment] 2022-01-06 15:24
Hello everyone,

I came to this thread because I have also found one feature to be missing - the [Ctrl + click] navigation to artifact poms.

However, I would like to point out that it only seems to not work properly when the artifact version (for example) is a property variable, which leads me to think that maybe the navigation feature simply isn't resolving those placeholders.

Concretely:

- if we have a dependency declaration like this, [Ctrl+click] navigation will not work
```
<dependency>
    <groupId>fish.payara.api</groupId>
    <artifactId>payara-bom</artifactId>
    <version>${payara-version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```
- if, however, we have an explicit version there, like this, it will correctly navigate.
```
<dependency>
    <groupId>fish.payara.api</groupId>
    <artifactId>payara-bom</artifactId>
    <version>5.2021.7</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

Hope this helps the resolution.

Also, thanks Eclipse team, by your efforts. 
The IDE just keeps getting better and better.

**Comment by askoog** [comment] 2022-01-09 21:07
I'd say the biggest problem with the new editor is how it handles dependencies and dependency management. In the previous editor, you could hover on a dependency with a managed version and see which version it resolved to and where it was managed. This feature is gone in the new editor which makes it rather unusable. The old editor also gave you warnings if you specified the same version of a dependency that already was managed, the new editor doesn't display any warnings at all as far as I can see.

Sadly, I have to use the legacy editor, the new one is missing too many crucial features

**Comment by mickaelistria** [comment] 2022-01-12 21:47
I'm closing this issue that is not the right grain for project development. Please open 1 dedicated issue, with example pom files, for each bug or limitation you may face. Please make sure you're trying latest snapshots of m2e before reporting.

**Closed by mickaelistria** 2022-01-12 21:47 UTC

**Comment by gerib** [comment] 2024-12-27 14:06
Re:

> * Format source doesn't work

see also [POM Editor formatting doesn't work #1907](https://github.com/eclipse-m2e/m2e-core/issues/1907).
