### ISSUE TITLE
application.properties file not copied into target output folder anymore

### ISSUE THREAD

**Issue by martinlippert** [eclipse-m2e/m2e-core#1148] opened 2022-12-19 17:37 UTC
I have a file called `application.properties` in the `src/main/resources` folder of my maven project, but the file doesn't get copied to the target output folder anymore. This worked with m2e 2.0.5, but does not work anymore with m2e 2.0.6 or m2e 2.1.2. Any idea what might be going wrong here?

As a sample project, I use a simple project generated via https://start.spring.io, selecting Java 17, Maven, Spring Boot 2.7.6 and the web and actuator starter.

First report of this appeared here: https://github.com/spring-projects/sts4/issues/929

**Comment by laeubi** [comment] 2022-12-19 18:56
I think the issue is the same as discussed here: 
- https://github.com/eclipse-m2e/m2e-core/discussions/1142

It would really help if someone can show the problem with a [minimal-reproducer](https://stackoverflow.com/help/minimal-reproducible-example) at best as a test-case for m2e so we can make sure such thing not happen again.

**Comment by KaRkY** [comment] 2022-12-21 11:14
I found out what the problem is. If I add ".mvn" folder at the root of the project then resources do not get copied over.

**Comment by HannesWell** [comment] 2022-12-30 22:39
#1150 is about the same issue, but contains a test-case. Therefore I'm closing this as duplicate and all further work is tracked with #1150.

**Comment by HannesWell** [comment] 2022-12-30 22:39
Duplicate of #1150

**Closed by HannesWell** 2022-12-30 22:39 UTC
