### ISSUE TITLE
Pom editor: select enclosing element not working

### ISSUE THREAD

**Issue by dstango** [eclipse-m2e/m2e-core#1315] opened 2023-03-17 09:55 UTC
Not sure if this is the right place to report it -- if not please advise me to a more appropriate github project.

The regular XML-Editor has the handy feature of "select enclosing element":
* Alt-Shift-Up: expands the current selection, e.g. (| representing the cursor, [ ] a range selection):
  `<maven.compiler.source>1|.8</maven.compiler.source>` -->   `<maven.compiler.source>[1.8]</maven.compiler.source>`  -->   `[<maven.compiler.source>1.8</maven.compiler.source>]`
* Alt-Shift-Down: does the opposite (restore last selection):
  `[<maven.compiler.source>1.8</maven.compiler.source>]` --> `<maven.compiler.source>[1.8]</maven.compiler.source>`  --> `<maven.compiler.source>1|.8</maven.compiler.source>`

This does not work in the pom editor.

**Comment by mickaelistria** [comment] 2023-03-17 09:59
Thanks for the report.
Reporting it here is a good start, but the issue is more generic to XML edition which is based on Wild Web Developer; so can you please clone it to https://github.com/eclipse/wildwebdeveloper/issues ? GitHub doesn't allow transferring to another organization.

**Comment by dstango** [comment] 2023-03-17 10:37
Are you sure? I tried to open the file with the regular XML editor and there it works. Wouldn't this editor be based on Wild Web Developer, too?

**Comment by mickaelistria** [comment] 2023-03-17 10:39
> the regular XML editor 

What do you call "the regular XML editor" ? Is it the same one you see for pom.xml?

**Comment by dstango** [comment] 2023-03-17 11:08
@mickaelistria I mean these two variations:
* Project Explorer -> right click on pom.xml -> "Open with" -> "Maven POM editor"
* Project Explorer -> right click on pom.xml -> "Open with" -> "XML editor"

The second option "XML editor" is *not* the same as the Maven POM editor, as it is lacking all the special tabs for "Dependencies", "Dependency Hierachy", etc. I'm wondering if this XML editor is also the Wild Web Developer editor, or not.
The syntax coloring looks slightly different -- yet the mentioned keyboard shortcuts in the ("regular") XML editor work.

**Comment by mickaelistria** [comment] 2023-03-17 11:15
OK, so the this confirms that the issue is in Wild Web Developer, which provides XML support for the text editor that is included in the Maven Pom Editor.

**Closed** 2023-03-18 23:10 UTC
