### ISSUE TITLE
1.19.0.20211116-0804 lost XML syntax coloring of pom.xml

### ISSUE THREAD

**Issue by dougbreaux** [eclipse-m2e/m2e-core#406] opened 2021-11-17 17:15 UTC
After accepting: 

`M2E - Maven Integration for Eclipse (includes Incubating components)	1.19.0.20211116-0804`

I no longer have the normal XML coloring of my pom.xml files. I seem to have lost the sub-module:

` M2E - POM Editor (Legacy) using WebTools SourceEditing UI	1.18.2.20211002-1029`

I was also unable to revert to what I had before: 

`M2E - Maven Integration for Eclipse (includes Incubating components)	1.18.3.20211018-0804`

```
!ENTRY org.eclipse.equinox.p2.engine 4 4 2021-11-17 11:04:34.866
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2021-11-17 11:04:34.866
!MESSAGE session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2021-11-17 11:04:34.866
!MESSAGE No repository found containing: org.eclipse.update.feature,org.eclipse.m2e.feature,1.18.3.20211018-0804
```

**Comment by mickaelistria** [comment] 2021-11-17 17:20
The WebTools editor is indeed removed by default. Is you file open using the "Generic Test Editor"? Do you have the `    M2E - POM Editor using LemMinX language server (includes Incubating components)` feature installed?

**Comment by dougbreaux** [comment] 2021-11-17 17:23
Have tried manually installing older version from Snapshots repo:
![image](https://user-images.githubusercontent.com/25640850/142250033-02f11f9a-3353-496e-b8d8-8db6a5d2591e.png)

I now have this hybrid-crazy that I'll probably come to regret, but that seems to be working so far:
![image](https://user-images.githubusercontent.com/25640850/142250212-3de00e1f-30d9-450e-9105-6a6129527ab3.png)

**Comment by dougbreaux** [comment] 2021-11-17 17:24
> 
> 
> The WebTools editor is indeed removed by default. Is you file open using the "Generic Test Editor"? Do you have the ` M2E - POM Editor using LemMinX language server (includes Incubating components)` feature installed?

Hmmm... I hadn't tried that LemMinX component. Guess I can try adding that.

**Comment by HannesWell** [comment] 2021-11-17 18:29
I also have the problem, that the installation of the m2e-LemMinX feature failed due to missing requirements.
My first guess is that the LemMinX requirements cannot be found because the providing repos are not listed in the available software sites because they are not among the usual ones.
But I will investigate in detail and report the results.
If this is indeed the cause we maybe could fix it with a corresponding repository reference in the m2e.site project.

**Comment by mickaelistria** [comment] 2021-11-17 18:35
Which requirements are missing?

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/eclipseide> developer, for Red Hat
Developers <https://developers.redhat.com/>

**Comment by HannesWell** [comment] 2021-11-17 19:26
When I try to install from `https://download.eclipse.org/technology/m2e/snapshots/latest/`
- M2E - Maven Integration for Eclipse (includes Incubating components)	1.19.0.20211116-0804
- M2E - POM Editor using LemMinX language server (includes Incubating components)	1.18.3.20211116-0804

into a fresh `Eclipse 2021-09 Modelling Tools` (it does not contain any m2e feature) the error at the Install Remediation Page is:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: M2E - POM Editor using LemMinX language server (includes Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.lemminx.feature.feature.group 1.18.3.20211116-0804)
  Missing requirement: M2E Maven POM File Editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.editor.lemminx 1.18.3.20211116-0804) requires 'osgi.bundle; org.eclipse.wildwebdeveloper.xml [0.13.1,0.14.0)' but it could not be found
  Cannot satisfy dependency:
    From: M2E - POM Editor using LemMinX language server (includes Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.lemminx.feature.feature.group 1.18.3.20211116-0804)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.editor.lemminx [1.18.3.20211116-0804,1.18.3.20211116-0804]
```
The important part is: `requires 'osgi.bundle; org.eclipse.wildwebdeveloper.xml [0.13.1,0.14.0)' but it could not be found`


After I have add https://download.eclipse.org/wildwebdeveloper/releases/0.13.1/ to the `Available Software Sites` I get the following error for the same request:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: M2E - POM Editor using LemMinX language server (includes Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.lemminx.feature.feature.group 1.18.3.20211116-0804)
  Missing requirement: M2E Maven POM File Editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.editor.lemminx 1.18.3.20211116-0804) requires 'osgi.bundle; org.eclipse.lsp4e 0.13.7' but it could not be found
  Cannot satisfy dependency:
    From: M2E - POM Editor using LemMinX language server (includes Incubating components) 1.18.3.20211116-0804 (org.eclipse.m2e.lemminx.feature.feature.group 1.18.3.20211116-0804)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.editor.lemminx [1.18.3.20211116-0804,1.18.3.20211116-0804]
```
The important part changed to `requires 'osgi.bundle; org.eclipse.lsp4e 0.13.7' but it could not be found`, so I added https://download.eclipse.org/lsp4e/releases/0.20.0/plugins/ and the installation is successful.

I think the problem is that m2e is the project that pulls in/provides the LemMinX dependencies to the download.e.o/releases/ repos:
- org.eclipse.wildwebdeveloper.xml
- org.eclipse.lsp4j
- org.eclipse.lsp4e

The current and up-comming release repos
- https://download.eclipse.org/releases/2021-09/202109151000/plugins/
- https://download.eclipse.org/releases/2021-12/202110291000/plugins/
... do not contain the required latest version of `org.eclipse.wildwebdeveloper.xml` and `org.eclipse.lsp4e`.

I assume that is because they only contain the versions that are required by the m2e-version which is included in those particular release(-candiate) builds. And that m2e-version is the latest release at that time, isn't it?
So the snapshots are always are ahead of their time.

This strengthens my initial assumption that repo-references in `org.eclipse.m2e.site/category.xml` to `https://download.eclipse.org/wildwebdeveloper/releases/0.13.1` and `https://download.eclipse.org/lsp4e/releases/0.20.0/`  can help in this regard and simplifies installation.
This is not ideal for us Devs because have to sync them manually with the TP, but I think we should take this burden for the users especially because LemMinX is the new default.

I'm about to test it.

**Comment by HannesWell** [comment] 2021-11-17 19:49
I had the same issue with my Oomph provisioned Eclipse that I use usually (but the error message was not that clear) and I think that that is also the reason why the included LemMinX-feature was not installed automatically. Looks P2 discards children without prominent notice if they cannot be installed.

The suggested change worked for me with a locally build repo added via file-URL as Available Update Site. Then also the LemMinX-feature is also installed automatically if I only select the 'main' m2e feature.

**Comment by dougbreaux** [comment] 2021-11-17 22:01
No idea how I'm going to recover from this now 😄 
![image](https://user-images.githubusercontent.com/25640850/142289445-9d57be35-f2ed-471f-932d-c7e045016c54.png)

**Comment by HannesWell** [comment] 2021-11-17 23:37
Sorry a lot of text. 😄
To make it short: Temporarily add the following repositories to the `Available Software Sites` in your preferences:
- https://download.eclipse.org/wildwebdeveloper/releases/0.13.1/ 
- https://download.eclipse.org/lsp4e/releases/0.20.0/plugins/

This is de-facto what my suggested change does and should allow you to install all m2e-features from the current snapshot.
If the others agree and my proposed change is merged you can remove them again.

**Closed** 2021-11-18 06:53 UTC

**Comment by HannesWell** [comment] 2021-11-18 09:21
The additional sites mentioned in my previous comment should not be necessary any more. You can remove them.
The feature `M2E - Maven Integration for Eclipse (includes Incubating components)` including the LemMinX sub-feature should now install flawlessly.

**Comment by dougbreaux** [comment] 2021-11-18 16:00
Sorry to continue here, but wondering if I now have a confused installation (and if that could be the source of another problem I'm having):
![image](https://user-images.githubusercontent.com/25640850/142450878-ef6bea21-bfbb-4f7d-b8e8-cb2b35627a5a.png)

**Comment by mickaelistria** [comment] 2021-11-18 16:33
> I now have a confused installation (and if that could be the source of another problem I'm having):

The installation doesn't seem too bad. What makes you think it is? What's the problem you're having?

**Comment by dougbreaux** [comment] 2021-11-18 17:22
Well, it looks like I have multiple versions of the exact same components above. (The problem I'm having is JUnit tests not seeing dependencies when run under Eclipse, despite compilation seeing them fine. But that's a different topic, just wasn't sure if I had a mismatched install that could be a cause, and I should try to remove & reinstall from scratch.)

**Comment by HannesWell** [comment] 2021-11-20 09:15
Actually your installation looks fine. I cannot see different versions of the same feature.

Please not that not all features have the same Major-Minor-Micro version because we use Semantic-Versioning and not all features have corresponding changes at the same time. So it is perfectly fine that the m2e.feature has version `1.19.0` while for example the m2e-SLF4J feature only has version `1.17.2`. Usually it can be assumed that, if the Installer does not complain about a Installation request and does not suggest changes, you have installed the requested version, which is usually the latest one available.

Furthermore I want to mention, that the `M2E-Complete Development Kit` (aka M2E-SDK) feature is intended to be used in target platforms of developers that develop other plug-ins based on m2e and not to be installed. It (now) contains all other m2e-features and their sources.
Additionally I think it is not a good idea to install both POM Editor features together, the new LemMinX one and the legacy one. I'm not sure if they might interfere with each other and could cause problems (@mickaelistria probably knows best about that).

Therefore I recommend you to uninstall the `M2E-Complete Development Kit` feature as well as the `M2E - POM Editor Legacy` Feature and just to keep `M2E - Maven Integration for Eclipse`, `M2E - POM Editor LemMinX`, `M2E - PDE` and `M2E - SLF4J over Logback Logging`.

**Comment by dougbreaux** [comment] 2021-11-20 17:21
@HannesWell Thanks for the follow-up. Things look cleaner now.

**Comment by bedcoding** [comment] 2023-01-01 07:52
![b1](https://user-images.githubusercontent.com/33927558/210164204-cb69ba4c-f7ac-448d-9485-bbf2d4360f87.jpg)
I'm having the same problem with version 2022-03.
Specifically, how should I solve it?

**Comment by mickaelistria** [comment] 2023-01-02 15:13
Please always ensure you're using latest release of everything first.
