### ISSUE TITLE
Project isn't converted to faceted form for war projects

### ISSUE THREAD

**Issue by theit** [eclipse-m2e/m2e-core#867] opened 2022-08-08 14:12 UTC
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-09 M2 (4.25.0 M2)
Build id: 20220804-1257
m2e: 2.0.1.20220805-1816

Background:
I have a multi-module project consisting of several submodules. Two of them (let's call them A and B) are jar projects, everything is buildable fine via command line Maven. Module A basically is a REST API that starts an embedded Jetty server, and B as a JavaScript application is deployed to Tomcat as a web application. So far this works.

To simplify life I wanted to convert both A and B to war projects to
a) get rid of the embedded Jetty server
b) be able to deploy both war projects to the same tomcat instance and
c) use WTP and a local Tomcat instance for b) to additionally be able to debug at least the REST part in module A.

Therefore I added to both pom.xml files `<packaging>war</packaging>` and m-war-p to the build/plugins section, and to both modules a `web.xml` file into `src/main/webapp/WEB-INF`. Via command line Maven builds both war modules fine.

The problem that I couldn't solve:

When I cleanup the Eclipse-specific files/folders (`.classpath`, `.project`, `.settings`) and reimport the modules into my workspace, m2e doesn't convert them to faceted form, and I cannot add them to a Tomcat server instance. I manually have to first right-click in the package explorer on the projects, Configure => Convert to Faceted Form... and select "Dynamic Web Module: 3.1". And second I have to go to "Deployment Assembly" tab in the project properties, click "Add..." => "Java Build Path Entries" and select "Maven Dependencies" because only the folders src/{main,test}/{java,resources} are shown in the web deployment assembly list.

Unfortunately when Maven => Update project is triggered at the entry "Maven Dependencies" is removed from the deployment assembly.

I haven'seen anything in the logs that indicates an error so I'm a bit lost what is causing this.

I also tried to add m2e-wtp 1.5.0.20220805-2025 from https://download.eclipse.org/m2e-wtp/snapshots/ hoping that this solves the problem, but this gave the following error trying to update the project after Eclipse restart;

```
!MESSAGE Duplicate lifecycle mapping metadata for MavenProject: com.example.A:local @ ...\A\pom.xml.
!STACK 0
org.eclipse.m2e.core.internal.lifecyclemapping.DuplicateLifecycleMappingMetadataException: Mapping defined in 'org.eclipse.m2e.jdt_2.0.0.20220706-1958 [834]' and 'org.eclipse.m2e.wtp_1.5.0.20220805-2025 [989]'
        at org.eclipse.m2e.core.internal.lifecyclemapping.SimpleMappingMetadataSource.getLifecycleMappingMetadata(SimpleMappingMetadataSource.java:87)
        at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:557)
        at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:251)
        at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateLifecycleMapping(LifecycleMappingFactory.java:197)
...
```

Any idea what is causing this?

**Comment by fbricon** [comment] 2022-08-08 15:21
Eclipse IDE for Enterprise Java and Web Developers 2022-09 M2 (4.25.0 M2) works. It embeds m2e-core 1.20.1 and m2e-wtp 1.4.4

**Comment by theit** [comment] 2022-08-09 07:14
> Eclipse IDE for Enterprise Java and Web Developers 2022-09 M2 (4.25.0 M2) works. It embeds m2e-core 1.20.1 and m2e-wtp 1.4.4

Indeed, this works (again), but comes with an older m2e-core and also an older embedded Maven (3.8.4 vs 3.8.6)...

**Comment by theit** [comment] 2022-08-09 07:58
I found a way to reproduce the behaviour:

Create a new empty project of type "General" and in the project a new file `pom.xml` having the following contents (no other files necessary):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>test</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>war</packaging>


	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
```

Right-click on the project -> Configure -> Convert to Maven Project

With Eclipse IDE for Java Developers 2209-M2 (using m2e-core 2.0.1), the project is not converted to faceted form, i.e. seems to be a plain Maven jar artifact project, and the `.project` file looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
        <name>test</name>
        <comment></comment>
        <projects>
        </projects>
        <buildSpec>
                <buildCommand>
                        <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
                        <name>org.eclipse.m2e.core.maven2Builder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
        </buildSpec>
        <natures>
                <nature>org.eclipse.jdt.core.javanature</nature>
                <nature>org.eclipse.m2e.core.maven2Nature</nature>
        </natures>
</projectDescription>
```

Using Eclipse IDE for Enterprise Java and Web Developers (using m2e 1.20.1), the correct project facets and natures for a dynamic web module 3.1 project are added:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
        <name>test</name>
        <comment></comment>
        <projects>
        </projects>
        <buildSpec>
                <buildCommand>
                        <name>org.eclipse.jdt.core.javabuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
                        <name>org.eclipse.wst.common.project.facet.core.builder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
                        <name>org.eclipse.wst.validation.validationbuilder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
                <buildCommand>
                        <name>org.eclipse.m2e.core.maven2Builder</name>
                        <arguments>
                        </arguments>
                </buildCommand>
        </buildSpec>
        <natures>
                <nature>org.eclipse.jem.workbench.JavaEMFNature</nature>
                <nature>org.eclipse.wst.common.modulecore.ModuleCoreNature</nature>
                <nature>org.eclipse.jdt.core.javanature</nature>
                <nature>org.eclipse.m2e.core.maven2Nature</nature>
                <nature>org.eclipse.wst.common.project.facet.core.nature</nature>
                <nature>org.eclipse.wst.jsdt.core.jsNature</nature>
        </natures>
</projectDescription>
```

**Comment by theit** [comment] 2022-08-09 08:20
@laeubi: As I mentioned initially I tried m2e-core 2.0.1 in combination with m2e-wtp 1.5.0, and this resulted in an error (DuplicateLifecycleMappingMetadataException).

By using the above sample project, converting it to a Maven project with Eclipse IDE for Java Developers having m2e-core 2.0.1.20220805-1816 and m2e-wtp 1.5.0.20220805-2025 installed, line 7 (the one with packaging=war) is marked with an error, and the description says:

Conflicting lifecycle mapping metadata (project packaging type="war"): Mapping defined in 'org.eclipse.m2e.jdt_2.0.0.20220706-1958 [834]' and 'org.eclipse.m2e.wtp_1.5.0.20220805-2025 [1023]'. To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration.

According to the error message it seems to me that at m2e-core claims to be responsible for this type of mapping, but not m2e-wtp.

**Comment by laeubi** [comment] 2022-08-09 08:27
1. You should get a Quick-Fix to choose what mapping to use
2. Both `m2e.jdt` and `m2e.wtp` seem to contain a mapping for the `war` packaging

I can't tell if `m2e.jdt` is "wrong" here or `m2e.wtp` should attach to the `m2e.jdt` type instead of providing a seperate one, nerveless `m2e.wtp` and `m2e.jdt` are recently updated to account for new API changes, and `m2e.wtp` was moved in this repository, so there might also be the case that something was not adjusted correctly, thus I think it would be good to also report this for `m2e.wtp` because according of its readme it is the one that

> Support for war projects : adds the Java and Dynamic Web Facets. Support war overlays and on-the-fly resource filtering

**Comment by theit** [comment] 2022-08-09 08:47
Yes, this allows me to either ignore m2e-core or m2e-wtp integration <packaging>war</packaging> in Eclipse preferences:

Ignoring the m2e-wtp one results in the already mentioned behaviour, i.e. no facets/natures added. Ignoring the one from m2e-core, then m2e-wtp seems to add the facets and natures, but two different errors now appear in the problems view:

Description: null (org.apache.maven.plugins:maven-war-plugin:3.3.2:war:default-war:package)

java.lang.IllegalStateException
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.getSession(MavenExecutionContext.java:364)
	at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.executeCopyResources(ResourceFilteringBuildParticipant.java:275)
	at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.build(ResourceFilteringBuildParticipant.java:98)
	at org.eclipse.m2e.wtp.internal.build.WarProjectBuildParticipant.build(WarProjectBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:168)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:113)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:219)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:104)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Resource: pom.xml
Path: /test
Location: line 21
Type: Maven Build Problem



Description: Unknown
Resource: pom.xml
Path: /test
Location: line 1
Tyoe; Maven Java EE Configuration Problem

I'll report this in m2e-wtp.

**Comment by theit** [comment] 2022-08-10 12:59
For the record: https://github.com/eclipse-m2e/m2e-wtp/issues/13

**Comment by mickaelistria** [comment] 2022-09-01 12:58
First issue (duplicated lifecycles) seems to be caused by https://github.com/eclipse-m2e/m2e-core/commit/8ed00a53d6dba5fb31e81765b73fbeea769fead4 (cc @HannesWell ): moving the `war` lifecycle mapping from `org.eclipse.m2e.lifecyclemapping.defaults` to `org.eclipse.m2e.jdt` causes that this lifecycle isn't assumed as being default (overridable) and conflicts later with m2e-wtp one instead of being ignored.

**Comment by HannesWell** [comment] 2022-09-01 13:17
> First issue (duplicated lifecycles) seems to be caused by [8ed00a5](https://github.com/eclipse-m2e/m2e-core/commit/8ed00a53d6dba5fb31e81765b73fbeea769fead4) (cc @HannesWell ): moving the `war` lifecycle mapping from `org.eclipse.m2e.lifecyclemapping.defaults` to `org.eclipse.m2e.jdt` causes that this lifecycle isn't assumed as being default (overridable) and conflicts later with m2e-wtp one instead of being ignored.

Good to know, I wasn't aware of that. Thanks for the investigation.

**Comment by mickaelistria** [comment] 2022-09-01 19:04
The part about m2e-core is resolved and will be released soon.
Further work is tracked on m2e-wtp issue.

**Closed by mickaelistria** 2022-09-01 19:04 UTC
