### ISSUE TITLE
An internal error occurred during: "Updating Maven Project".

### ISSUE THREAD

**Issue by GAEREL** [eclipse-m2e/m2e-core#1663] opened 2024-02-01 13:37 UTC
Hello.

I have the message everytime I try to update a maven project

![image](https://github.com/eclipse-m2e/m2e-core/assets/43636651/b28d81a0-d89d-428e-b88d-fc34d1ba06a3)

Maven is : 
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: K:\opt\java\j2ee\apache-maven-3.9.6
Java version: 17.0.9, vendor: Oracle Corporation, runtime: K:\opt\java\j2se\jdk-17.0.9
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

Eclipse is : 
Version: 2023-12 (4.30.0)
Build id: 20231201-2043

the full message is : 
An internal error occurred during: "Updating Maven Project".
'org.eclipse.core.resources.IProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getProject()'

No message in maven console...

Maven settings in Eclipse seems ok...

Thanks for your help

**Comment by HannesWell** [comment] 2024-02-03 00:26
Is there anything helpful regarding this event in the error-log view?

**Comment by ksanjeev9211** [comment] 2024-02-16 04:08
I have been also getting the same issue for quite some time now.

Java version: 21.0.2, vendor: eclipse justj,
OS name: "windows 10"

![image](https://github.com/eclipse-m2e/m2e-core/assets/4118153/75978178-0c9d-4b52-b541-f5c25a36c754)


Following  stack trace is printed in the .metadata/.log



<details>
<summary>StackTrace</summary>

!ENTRY org.eclipse.core.jobs 4 2 2024-02-15 21:56:57.182
!MESSAGE An internal error occurred during: "Updating Maven Project".
!STACK 0
java.lang.NoSuchMethodError: 'org.eclipse.core.resources.IProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getProject()'
	at org.jboss.tools.maven.apt.internal.AbstractAptProjectConfigurator.configureRawClasspath(AbstractAptProjectConfigurator.java:154)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:209)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:167)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:503)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:497)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:425)
	at java.base/java.util.Collection.removeIf(Collection.java:583)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:413)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1097)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

</details>

**Comment by ksanjeev9211** [comment] 2024-02-16 04:14
Unfortunately, I have been getting this error for quite some now, not sure what to be done.  Following is the stack trace in the .log or error-log:

![image](https://github.com/eclipse-m2e/m2e-core/assets/4118153/1af35407-ba1e-4d6b-80e0-731bc12bd9f6)

**Comment by laeubi** [comment] 2024-02-16 05:12
> Unfortunately, I have been getting this error for quite some time now, not sure what to be done. Following is the stack trace in the .log or error-log:

Copy this as text is maybe more useful, but beside that it seems you are using jboss tools and it is incompatible with current m2e release.

**Comment by ksanjeev9211** [comment] 2024-02-16 06:07
True, I just removed them and the problem is resolved.

Thanks for help and  quick reply.

**Comment by akurtakov** [comment] 2024-02-16 07:32
Closing as there is nothing ot be done on m2e side.

**Closed by akurtakov** 2024-02-16 07:32 UTC
