### ISSUE TITLE
IllegalArgumentException nullifies all POM editor autocomplete features

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [eclipse-m2e/m2e-core#1195] opened 2023-01-12 13:01 UTC
# Description #
----------

Hello there, 

I have just fresh installed Eclipse 2022-12 (the current latest) and fresh installed Payara Tools 2.0.0Beta1.

Immediately after installing Payara Tools, most things in POM editor (M2E, I think) has started behaving unexpectedly, **breaking autocomplete**, **breaking move to other POMS** and all around just **throwing exceptions to the Error Log**.

It's most common complaints are:
1. ` java.lang.IllegalArgumentException: URI is not absolute`
2. ` A URL object was not found for the given URI dtds/sun-application_1_3-0.dtd from  fish.payara.eclipse.tools.server`

This effectively nulls the XML tools for Maven integration.

Although this issue is related to the installation of 3rd party plugin, the problem is that when that plugin is installed, it pretty much throws an **IllegalArgumentException** because it can't find a DTD schema (I think) and then the whole POM editor auto-completion features are rendered unusable.

## Expected Outcome ##

I expect that when there is an issue with a missing DTD schema from any third party it won't crash the whole POM editor.

## Current Outcome ##

When that particular plugin is installed, it is likely missing something so any navigation on the POM starts throwing Exceptions, for example:

1. When hovering over any part of the POM. Here I am hovering over this dependency. It writes those logs on the Erro Log:
![image](https://user-images.githubusercontent.com/2636004/212066061-349c5c1c-3818-4737-8342-a10caea79f15.png)

2. On the same screen (POM editor) right click and navigate to Code Actions:
![image](https://user-images.githubusercontent.com/2636004/212066377-7b97b80e-54ac-4dd3-a4e1-f239515ddd09.png)

3. On the Preferences Menu select XML(Wild Web Developer) and then Catalog and this happens:
![image](https://user-images.githubusercontent.com/2636004/212066991-f8b6744b-9326-4ff6-9695-4ec8b36c7fff.png)

In sum, it pretty much renders POM editor unusable, because it also **stops every other auto-completion to be suggested**.

## Steps to reproduce ## 

This is simple REST app written for Payara Micro, you can check it out [here](https://github.com/CarlosMOGoncalves/eclipse-issue-tester.git).

1. Install Eclipse IDE for Enterprise Java and Web Developers 2022-12
2. Install Payara Tools 2.0.0Beta1 (https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest)
3. Checkout that application
4. Open its POM and just perform some of the steps I have pointed above

**Final note**

- sorry for all the Issue ceremony. I used the template from Payara issues as I think it is pleasant to work with
- I understand that the Payara Plugin is really out of your scope. However, I think that if that plugin is missing something which ends up throwing an exception on M2E, you probably can do something about it that doesn't ruin the whole thing. It can happen with any other plugin and although I do not know what impacts it might have, it shouldn't really destroy the POM functionality.

## Environment ##
- **Distribution**:  Eclipse IDE for Enterprise Java and Web Developers 2022-12 2022-12 for Windows x64
- **JDK Version**: Corretto JDK 11
- **Operating System**:  Windows 10

**Comment by mickaelistria** [comment] 2023-01-12 13:09
Can you please check in workspace/.metadata/.log for a more complete stacktrace of this failure if available?
I remember about this bug a while ago and some fix was implemented; it looks like it could be incomplete.

**Comment by CarlosMOGoncalves** [comment] 2023-01-12 14:43
Sure thing.
A clean log will print this exact text, multiple times:

```
!ENTRY org.eclipse.wildwebdeveloper.xml 2 0 2023-01-12 14:41:31.008
!MESSAGE A URL object was not found for the given URI dtds/sun-application_1_3-0.dtd from  fish.payara.eclipse.tools.server

!ENTRY org.eclipse.lsp4e 4 0 2023-01-12 14:41:31.009
!MESSAGE java.lang.IllegalArgumentException: URI is not absolute
!STACK 0
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.fromURI(URL.java:721)
	at java.base/java.net.URI.toURL(URI.java:1139)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.createURI(XMLCatalogs.java:149)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.lambda$3(XMLCatalogs.java:72)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getWTPExtensionCatalog(XMLCatalogs.java:68)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getAllCatalogs(XMLCatalogs.java:53)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLPreferenceServerConstants.storePreferencesToLemminxOptions(XMLPreferenceServerConstants.java:136)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.mergeCustomInitializationOptions(XMLLanguageServer.java:197)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:175)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

!ENTRY org.eclipse.lsp4e 4 0 2023-01-12 14:41:31.010
!MESSAGE java.lang.IllegalArgumentException: URI is not absolute
!STACK 0
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.net.URL.fromURI(URL.java:721)
	at java.base/java.net.URI.toURL(URI.java:1139)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.createURI(XMLCatalogs.java:149)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.lambda$3(XMLCatalogs.java:72)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getWTPExtensionCatalog(XMLCatalogs.java:68)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getAllCatalogs(XMLCatalogs.java:53)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLPreferenceServerConstants.storePreferencesToLemminxOptions(XMLPreferenceServerConstants.java:136)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.mergeCustomInitializationOptions(XMLLanguageServer.java:197)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:175)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
```

**Comment by mickaelistria** [comment] 2023-01-16 15:50
The root cause is in Payara Eclipse plugin defining and incorrect catalog. In https://github.com/eclipse/wildwebdeveloper/pull/1058 , I try to make Wild Web Developer (providing the XML editor) more tolerant of such errors.
There is nothing m2e can/should fix here; so I'm closing. Further discussions about the Eclipse side of things should happen on Wild Web Developer support channel (ie GitHub issues).

**Closed by mickaelistria** 2023-01-16 15:50 UTC
