### ISSUE TITLE
Unable to open custom parent pom

### ISSUE THREAD

**Issue by c-koell** [eclipse-m2e/m2e-core#438] opened 2021-12-09 14:55 UTC
In Eclipse 2021-09 (m2e 1.18.1) it was possible to open the parent pom on hover with CTRL.

In the newest Eclipse 2021-12 (m2e 1.19) no hyperlink is shown. If i try to open the parent pom in the Overview Tab i get following exception.
![Overview-Editor](https://user-images.githubusercontent.com/4134346/145419126-fb3a7267-0724-433b-ae59-6b8ff939a869.png)

This is the Exception
![Error](https://user-images.githubusercontent.com/4134346/145419318-74fb1d8e-b4bb-4e5e-a8e2-2690177e4d2f.png)

**Comment by c-koell** [comment] 2021-12-16 06:37
If we try to open the pom.xml from the Version History View (SubClipse) we get the same exception !

**Comment by mickaelistria** [comment] 2022-01-20 18:08
Duplicate of #501

**Closed by mickaelistria** 2022-01-20 18:08 UTC
