### ISSUE TITLE
Discovery catalog: FileNotFoundException when downloading org.eclipse.m2e.discovery.oss-catalog-1.13.jar

### ISSUE THREAD

**Issue by jschrod** [eclipse-m2e/m2e-core#184] opened 2021-05-03 22:21 UTC
This is a fresh install of Eclipse J2EE 2021-03.
Debian 10, OpenJDK 11, Internet connection without proxy.

The m2e connector catalog discovery URL is https://download.eclipse.org/technology/m2e/discovery/directory-1.15.xml.
In this XML document, the catalog URL is declared as https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar.

When I klick on _Open Catalog_ in Window / Preferences / Maven / Discovery, Eclipse tries to download this file.
This leads to a `FileNotFoundException`, as logged in .metadata/.log:

    !MESSAGE Cannot download bundle at https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar: https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar
    !STACK 0
    java.io.FileNotFoundException: https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar
            at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:303)
            at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.checkException(FileInfoReader.java:221)
            at org.eclipse.equinox.internal.p2.transport.ecf.FileInfoReader.getRemoteFiles(FileInfoReader.java:112)

(I discarded the rest of the stacktrace.)

Internet connection at the system works:

    pixel:.metadata $ wget https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar
    --2021-05-03 20:50:18--  https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar
    Resolving dl.bintray.com (dl.bintray.com)... 3.124.41.190, 3.125.168.216
    Connecting to dl.bintray.com (dl.bintray.com)|3.124.41.190|:443... connected.
    HTTP request sent, awaiting response... 403 Forbidden
    2021-05-03 20:50:18 ERROR 403: Forbidden.

The wget might be missing some HTTP request header to result in a HTTP status of 403; so I wouldn't count on it telling the availability of that file.

Is the catalog jar really available at this bintray download site?
Can I download it somewhere else? I'm able to establish a fake download site for the installation; but I would need to get the content first.
Can I use `oss-catalog-1.6.jar`, which was the catalog URL up to `directory-1.10.xml`?

Btw: In the end, I want to install m2e connectors for ANTLR and build-helper; in case someone can tell me another possibility to do so.

**Comment by keilw** [comment] 2021-05-06 12:03
We saw the same in an Eclipse 2020-06 installation which (because it's the last one running on Java 8) the client cannot change for another few years.

**Comment by laeubi** [comment] 2021-05-06 12:07
Why one needs a IDE that runs on java 8? Anyways bintray is shutting down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ I don't know if there is any alternative storage for the project right now.

**Comment by keilw** [comment] 2021-05-06 12:09
It cannot explain all the details here, but if you ever worked with SOAP messages (and the majority of real big businesses, whether it's banks, insurance retail or healthcare do) and tried to migrate that to Java 11 you would understand why this is not so trivial. 
And now think of one of the largest companies in the world with ten thousands of SOAP services and an Eclipse RCP client consuming them, then the answer comes by itself.

**Comment by laeubi** [comment] 2021-05-06 12:30
Well but all this don't affects the JVM used to **RUN** the ide, one can still develop J8 code with a J8 JVM and run recent Eclipse with J11+ ...

> it only supports 2020-12 but that is not acceptable for Hundred Thousands of users worldwide

If just one percent of those 'Hundred Thousands' would start contribute to Eclipse/m2e I don't see an issue to even support older releases :-)

**Comment by laeubi** [comment] 2021-05-06 12:42
> The m2e connector catalog discovery URL is https://download.eclipse.org/technology/m2e/discovery/directory-1.15.xml.
> In this XML document, the catalog URL is declared as https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar.

I have checked the link and it is already updated to the https://github.com/takari/m2e-discovery-catalog/raw/gh-pages/catalogs/org.eclipse.m2e.discovery.oss-catalog-1.13.jar which works for me.

I can't tell if this was recently updated, so please retry if the problem is gone.

**Comment by keilw** [comment] 2021-05-06 12:47
I do this for all my Open Source projects most of which were affected by the JFrog Greed measure, too, see: 
- https://github.com/unitsofmeasurement/uom-parent/issues/24
- https://github.com/JavaMoney/javamoney-parent/issues/6 (currently blocked by Travis-CI because the deployment of Snapshots to Sonatype has issues the others do not face)
- https://github.com/OpenDDRmobi/openddr-parent/issues/2 (where we also moved to GitHub downloads or pages instead of Bintray for the device repository, it no longer shows the download stats per month but it works)

How do you get the new cagalog URL:  https://github.com/takari/m2e-discovery-catalog/raw/gh-pages/catalogs/org.eclipse.m2e.discovery.oss-catalog-1.13.jar 
Does that require brand new versions of Eclipse or the related plugins or is there a way to configure this?
Because in the preferences that field is read-only.

**Comment by fbricon** [comment] 2021-05-06 12:50
I just updated the catalog jar urls

You can point to another catalog by adding -Dm2e.discovery.url=... to your eclipse.ini

**Comment by jschrod** [comment] 2021-05-06 12:51
With the updated discovery, it seems to work now; I get the connectors listed.

@laeubi 
> I can't tell if this was recently updated,

The discovery file was updated 2021-05-06 12:27:01 UTC; i.e., some 80 minutes ago. ;-)

**Comment by laeubi** [comment] 2021-05-06 12:52
> The discovery file was updated 2021-05-06 12:27:01 UTC; i.e., some 80 minutes ago. ;-)

Great and thanks @fbricon I'll close the issue then as fixed, please open another one if you still see specific problems with the updated URLs.

**Comment by fbricon** [comment] 2021-05-06 12:52
@keilw you need to restart eclipse. p2 has a tendency to aggressively cache remote metadata

**Closed by laeubi** 2021-05-06 12:52 UTC
Labels: question

**Comment by keilw** [comment] 2021-05-06 12:53
Ok it looks like in the browser the file changed. Will test it in a local Eclipse 2020-06.
If that works consistently for everyone then most likely our colleagues at the client have another problem with the proxy and github, but there should be someone to address that if it accepted bintray.com earlier.
