### ISSUE TITLE
No extension found error after opening m2e marketplace

### ISSUE THREAD

**Issue by mcoufal** [eclipse-m2e/m2e-core#194] opened 2021-05-11 14:08 UTC
Every time I open m2e marketplace, an error pops up saying that discovery was completed without finding any extensions. Only after I dismiss the error, extensions are found and shown in m2e marketplace.

How to reproduce:
1) run eclipse
2) open m2e marketplace

My configuration:
Eclipse Platform
Version: 2021-06 (4.20)
Build id: I20210508-1800
Java version: 11.0.11
Maven Integration for Eclipse	1.17.2.20210219-1922	org.eclipse.m2e.feature

![error](https://user-images.githubusercontent.com/26609411/117829059-ae95c980-b272-11eb-90bd-55bcf6b195d2.png)
[workspace.log](https://github.com/eclipse-m2e/m2e-core/files/6459749/workspace.log)

**Comment by mickaelistria** [comment] 2021-06-01 14:19
Could this be related to https://github.com/eclipse-m2e/m2e-core/issues/200#issuecomment-851548165 ?

**Comment by mcoufal** [comment] 2021-06-01 14:42
Looks to me that it's the same issue.

**Comment by mickaelistria** [comment] 2021-06-08 12:24
@fbricon I believe the catalogs are fixed. Can you please trigger the deployment? (and also describe the necessary steps so this can be performed by other committers)

**Comment by fbricon** [comment] 2021-06-08 17:14
Deployment is automatic after changes are merged in the master branch. But catalog deployment is currently failing https://github.com/takari/m2e-discovery-catalog/runs/2776298839?check_suite_focus=true
No idea why

**Comment by fbricon** [comment] 2021-06-08 18:06
deployment is fixed. But the "no extensions found" error followed by the list of extension error remains

**Comment by mickaelistria** [comment] 2021-06-09 14:45
I believe a change on how GitHub serves file is the root cause of this popup: https://github.community/t/last-modified-not-set-for-github-com-nor-raw-githubusercontent-com-https-requests/184296
I see the Last-Modified is still present on GitHub sites; so maybe we should enable the GitHub site for takari/m2e-discovery-catalog and use the new URL?

**Comment by mickaelistria** [comment] 2021-06-09 15:01
> I believe a change on how GitHub serves file is the root cause of this popup: https://github.community/t/last-modified-not-set-for-github-com-nor-raw-githubusercontent-com-https-requests/184296 I see the Last-Modified is still present on GitHub sites; so maybe we should enable the GitHub site for takari/m2e-discovery-catalog and use the new URL?

False alarm, this doesn't seem related. The missing Last-Modified does generate a warning but download still happens.

**Comment by mickaelistria** [comment] 2021-06-09 15:36
The root cause can be that https://download.eclipse.org/technology/m2e/discovery/directory-1.15.xml missies `permitCatagories=true`. What's the process to change that?

**Comment by fbricon** [comment] 2021-06-09 17:14
I use [CyberDuck](https://cyberduck.io/) to scp updates to build.eclipse.org. I fixed it. Works now

**Closed** 2021-06-10 10:04 UTC
