### ISSUE TITLE
Can't open pom files

### ISSUE THREAD

**Issue by doggy-dev** [eclipse-m2e/m2e-core#1549] opened 2023-09-16 08:06 UTC
I've just updated eclipse and now I cannot open any pom files anymore. I must say the maven integration in eclipse got very crappy since a couple of releases.

java.lang.IllegalThreadStateException
	at java.base/java.lang.Thread.start(Thread.java:793)
	at org.eclipse.tm4e.core.model.TMModel.startTokenizerThread(TMModel.java:249)
	at org.eclipse.tm4e.core.model.TMModel.addModelTokensChangedListener(TMModel.java:223)
	at org.eclipse.tm4e.ui.text.TMPresentationReconciler$InternalListener.textChanged(TMPresentationReconciler.java:332)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2789)
	at org.eclipse.jface.text.TextViewer.fireRedrawChanged(TextViewer.java:4999)
	at org.eclipse.jface.text.TextViewer.enabledRedrawing(TextViewer.java:5039)
	at org.eclipse.jface.text.TextViewer.setRedraw(TextViewer.java:5091)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.catchupWithProjectionAnnotationModel(ProjectionViewer.java:978)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.lambda$0(ProjectionViewer.java:891)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by HannesWell** [comment] 2023-09-16 08:29
This is not directly an m2e issue, but an issue in tm4e, which m2e depends on for the pom-Editor integration:
https://github.com/eclipse/tm4e/issues/578

The issue is already fixed and released so, the question is to which version of Eclipse and especially tm4e you have updated?

> I must say the maven integration in eclipse got very crappy since a couple of releases.

You can help to improve that by using the latest snapshot builds of m2e and its dependencies and report issues early or help fixing them. Every help is more than welcome. :)

**Comment by doggy-dev** [comment] 2023-09-16 08:40
It seems it was an update gone wrong. I had to add a couple of update sites to the available update sites so I get the correct updates regardless I made a fresh install of eclipse 2023-06.

This is not how I expect an update to work and a fresh install and configuring every 3 months is not an option.

**Comment by HannesWell** [comment] 2023-09-16 08:58
I don't know which update sites you have configured, but the [m2e latest release p2-repo](https://download.eclipse.org/technology/m2e/releases/latest/) has references to the repos of its dependencies, so they should be available implicitly if you have the m2e repo configured.

Btw. the latest simultaneous release is 2023-09, which also includes the latest m2e and its dependencies that provide the pom-Editor integration.

> This is not how I expect an update to work and a fresh install and configuring every 3 months is not an option.

What are the specific improvements you suggest?

**Comment by doggy-dev** [comment] 2023-09-16 09:17
I see you're being polite regardless of my rude tone and I appreciate it. Sorry for that, I was frustrated.

I've added 
https://download.eclipse.org/lsp4e/releases/latest
https://download.eclipse.org/releases/latest
https://download.eclipse.org/lsp4j/updates/releases/latest

I'm not sure anymore if these are all the sites. The last one doesn't seem to exist - it was just me trying to get it working.
Unfortunately I'm not exactly sure about the sites list I've added or enabled to get it working. If there is any way to find out what I've done, let me know.

I would have expected that adding update sites is not needed to update my eclipse and they are preconfigured so that just selecting update in the menu does everything automatically. Is it not suppose to work like that?

**Comment by HannesWell** [comment] 2023-09-16 14:26
> I see you're being polite regardless of my rude tone and I appreciate it. Sorry for that, I was frustrated.

Well I can understand that it can sometimes be frustrating, but M2E is mainly supported by volunteers, so we cannot provide the speed and quality assurance testing like a commercial product does. Therefore it is much more important for us to have more users testing the latest snapshots before they are released. The earlier we notice regressions from changes the higher the chances are that they can be fixed (or in the worst case the change is reverted).


> I've added
> https://download.eclipse.org/lsp4e/releases/latest
> https://download.eclipse.org/releases/latest
> https://download.eclipse.org/lsp4j/updates/releases/latest

All those repos are referenced in their specific version used in the m2e target-platform by the time the repo was build.
For lsp4j there is no latest, only specific releases:
https://download.eclipse.org/lsp4j/updates/releases/0.21.1/

> I would have expected that adding update sites is not needed to update my eclipse and they are preconfigured so that just selecting update in the menu does everything automatically. Is it not suppose to work like that?

We recently changed the m2e-feature to automatically add the m2e latest p2-repo to the available update-sites when it is installed. Probably this was not yet done in the older version, but should be fixed for now and the future.

In general m2e also participates in the Eclipse Simultaneous Release and is together with its dependencies contained in https://download.eclipse.org/releases/latest/ or the specific versions.

You can of course also use the Eclipse-Installer (provided by Eclipse Oomph) to provision your IDE and keep it up to date. The installer is also backed by the SimRel repository and you can either choose a specific version or the latest release or latest (Milesonte/Release-Candidate).

Since you mentioned that your problem is solved I'll close this.

**Closed by HannesWell** 2023-09-16 14:26 UTC
