### ISSUE TITLE
Problem with macen archiver on project refresh

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#827] opened 2022-06-30 09:45 UTC
I'm currently integrate the test for maven archiver but one (existing) fails now because it seems there is a bug in the mavenarchiver but I don't understand what has to be changed here:
```
java.lang.IllegalArgumentException: Path must include project and resource name: /projectimport
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2156)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.m2e.mavenarchiver.internal.AbstractMavenArchiverConfigurator.mavenProjectChanged(AbstractMavenArchiverConfigurator.java:226)
	at org.eclipse.m2e.mavenarchiver.internal.AbstractMavenArchiverConfigurator.mavenProjectChanged(AbstractMavenArchiverConfigurator.java:219)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:858)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:833)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:988)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:329)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:256)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:166)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
```

Can someone take al look at the code in `AbstractMavenArchiverConfigurator.mavenProjectChanged` and maybe adjust it? It seems somehow the path is not constructed correctly in `org.eclipse.m2e.mavenarchiver.internal.AbstractMavenArchiverConfigurator.getOutputDir(IMavenProjectFacade)`

**Comment by HannesWell** [comment] 2022-06-30 22:40
The problem is that in `BuildPathManagerTest.test431080_flatDirectoryLayout` the project being build (`projects/431080_flatDirectoryLayout/pom.xm`l) has a flat layout:
```
  <build>
    <sourceDirectory>${project.basedir}</sourceDirectory>
    <outputDirectory>${project.basedir}</outputDirectory>
  </build>
```
Which has the consequence that the `IMavenProjectFacade.getOutputLocation()` returns a path with only one segement, the project name. But all children of the workspace-root are `IProjects`. So one either needs a path with at least two segments pointing to a 'real' folder within a project or can use WorkspaceRoot.getProject().
I applied the latter approach with an additional commit of PR #820, which should fix this issue (at least locally it did).

**Comment by laeubi** [comment] 2022-07-01 04:21
Great do you think we should apply your cleanup just right now? Or merge the tests "as-is" and then fix them with your cleanup? Or something in between by applying the fix for flat projects first?

**Comment by HannesWell** [comment] 2022-07-01 06:14
> Great do you think we should apply your cleanup just right now? Or merge the tests "as-is" and then fix them with your cleanup? Or something in between by applying the fix for flat projects first?

At the moment I have a dedicated commit in that PR to fix this issue. Since it would have to be applied at multiple locations when done before the clean-up I suggest to keep it after the clean-up commit. Furthermore the clean up is not flawed if the bug was there before and the tests are ok as well since its a bug that has to be fixed in m2e-core.
Long story short: I suggest we (or you?) merge the tests as is  now. Then I squash the commits of PR #820 two have two commits (one clean up and one to fix this) and submit this with _rebase-and-merge_, and everything should be fine.

**Closed** 2022-07-01 07:19 UTC
