### ISSUE TITLE
Editor won't display info or allow for navigation in dependencyManagement

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [eclipse-m2e/m2e-core#840] opened 2022-07-05 17:02 UTC
# Description #

When hovering over a dependency which has its version written as replacement variable which in turn has its value in the `<properties>` element of a pom and that dependency is inside the `<dependencyManagement>` element, the editor won't display any information regarding it.

Further, it won't allow navigation to the given POM using `Ctrl+Click`.

This won't happen if the dependency is inside the `<dependencies>`  element, in which case it will display the info tooltip about it and `Ctrl+Click` will navigate to the matching pom.

## Expected Outcome ##

On one such dependency the editor should be able to display the info tooltip about it and allow for the navigation to it, with `Ctrl+Click`.
This is very useful when one is trying to check dependencies versions or properties in an imported BOM.

## Current Outcome ##

Hovering won't show info tooltip and Ctrl+Click on it won't navigate to matching pom.
This happens when the dependency is within a `<dependencyManagement>` element.

## Steps to reproduce ## 

I have a sample project that I use for other issues [here](https://github.com/CarlosMOGoncalves/payara-jdk-tester).
This is a rather simple app with some dependencies. It has 3 branches, one for each LTS of JDK.

1. Download Eclipse IDE 2022-06 for Enterprise Java and Web Developers Windows x64 [here](https://www.eclipse.org/downloads/packages/)
2. checkout above project
3. import it to eclipse
4. navigate to pom.xml
5. hover over any dependency inside the dependencies management element , like `fish.payara.api`
6. now `Ctrl+Click` on it
7. It won't navigate to the matching pom
8. now hardcode the version, for example 5.2022.2, and try again
9. should now be possible to see info and navigate
10. compare with any dependency on the `<dependencies>`  element

## Environment ##

- **Eclipse Version**: Eclipse IDE for Enterprise Java and Web Developers 2022-06
- **Plugins**: Payara Tools and SonarLint
- **M2E Version**:  1.20.1.20220227 (the one that comes bundled)
- **Maven Version**: 3.8.5
- **JDK Version**: OpenJDK Corretto 1.8.0_322
- **Operating System**: Windows 10

**Comment by CarlosMOGoncalves** [comment] 2022-07-05 17:23
Hello @mickaelistria ,

I have left a sample project from my Github. 
It contains the needed pom.xml for those reproducing instructions.

**Comment by mickaelistria** [comment] 2022-07-06 15:44
I think this is already fixed in snapshots and I cannot reproduce it. Can you please try installing latest m2e from https://download.eclipse.org/technology/m2e/snapshots/latest/ and report whether this fixes your issue?

**Comment by CarlosMOGoncalves** [comment] 2022-07-06 16:18
You are right @mickaelistria ,
I installed the snapshot for **POM Editor using LemMinX** and it is indeed **working perfectly**.
Many thanks Mickael, this can be closed.

However, risking stretching your help a bit further let me just ask you one thing:
I didn't install the complete bundle of modules within the update site you sent because somehow Eclipse would unistall Payara Tools and some other components in order to upgrade M2E. 
Do you have an idea why? 
And whether this will happen when the new version is released? Because I need at least those Payara Tools in the IDE.

![image](https://user-images.githubusercontent.com/2636004/177597004-a44d2983-111a-45b2-bf8d-7fe1e728c485.png)

**Comment by HannesWell** [comment] 2022-07-06 20:07
If you select the option at the bottom "Show original error and build my own solution" it shows a detailed description of probably conflicting dependencies from which your question can hopefully be answered.

But my first guess is, that thos Features have plug-ins that require m2e below 2.0

**Comment by CarlosMOGoncalves** [comment] 2022-07-07 00:04
Hi @HannesWell 
and thanks for the answer. 

I think you would be right, this is what I see then

![image](https://user-images.githubusercontent.com/2636004/177662148-899383c4-f1f4-4b60-912a-6d040ea477c5.png)

From what I get Maven JPA configurator needs org.eclipse.m2e.core below 2.0.0.
However, I see no mention to those first components JAX-RS, JSF  and to Payara Tools.
Are those details not complete? Or am I reading it wrong?

**Comment by HannesWell** [comment] 2022-07-09 11:28
> From what I get Maven JPA configurator needs org.eclipse.m2e.core below 2.0.0. However, I see no mention to those first components JAX-RS, JSF and to Payara Tools. Are those details not complete? Or am I reading it wrong?

Yes you are reading it right and it looks like the details are incomplete.
But my strong guess is that the ones not mentioned depend on the JPA configurator. But you can check the 'manually'.

**Comment by mickaelistria** [comment] 2022-07-10 20:16
Please try installing newer connectors from https://ci.eclipse.org/m2e/view/m2e-wtp/job/m2e-wtp/job/master/7/artifact/org.eclipse.m2e.wtp.site/target/repository/

**Closed** 2022-07-11 11:38 UTC
