### ISSUE TITLE
m2e using incorrect java.home to resolve dependency - failing dependency resolution

### ISSUE THREAD

**Issue by demlik** [eclipse-m2e/m2e-core#1050] opened 2022-11-09 12:11 UTC
- Using a version of Eclipse which can no longer run using Java 8 i.e.  2022-09 / latest
- Add JDK 1.8 to installed JRE and set as default
- Create a maven project with following pom.xml:

`
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.demo</groupId>
	<artifactId>bug</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<java.tools.version>1.8</java.tools.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>com.sun</groupId>
			<artifactId>tools</artifactId>
			<version>${java.tools.version}</version>
			<scope>system</scope>
			<systemPath>${java.home}/../lib/tools.jar</systemPath>
		</dependency>
	</dependencies>
</project>`
Result:
m2e fails to resolve system dependency as  ${java.home} is resolving to home of Java untime used by eclipse instead of the selected JDK1.8

Workaround:
Override ${java.home} as a property in settings.xml  / pom.xml and point to correct JDK directory - not sure how safe this is.

**Comment by hazendaz** [comment] 2022-12-04 18:30
why would one define obsolete tools jar in such a way.  That artifact doesn't need defined in example here.  Its part of java already at version 8 and doesn't exist since.  Usage of anything 'system' scope is flagged by maven.  What was not stated in this was maven version used.  Not 100% this m2e issue.  A better example would be useful.  There are lots of problems with java setup in general but that one doesn't feel related.  I'm linking it to a bigger java issue though just for reference.

**Comment by kwin** [comment] 2022-12-10 10:21
This is a duplicate of #248.

**Comment by HannesWell** [comment] 2023-02-28 23:15
Duplicate of #248

**Comment by HannesWell** [comment] 2023-02-28 23:16
Closing as duplicate. Please use #248 to further discuss and track this issue.

**Closed** 2023-02-28 23:16 UTC
