### ISSUE TITLE
Test failure at 	at org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsoleHasOutput(ConsoleTest.java:61) in mvn clean verify build

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#431] opened 2021-12-08 09:49 UTC
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.883 s <<< FAILURE! - in org.eclipse.m2e.core.ui.tests.AllTests
testConsoleHasOutput(org.eclipse.m2e.core.ui.tests.ConsoleTest)  Time elapsed: 2.857 s  <<< FAILURE!
java.lang.AssertionError: missing output in console
	at org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsoleHasOutput(ConsoleTest.java:61)

**Comment by HannesWell** [comment] 2021-12-08 10:12
This is a duplicate of #341.

**Closed by HannesWell** 2021-12-08 10:12 UTC
Labels: duplicate
