### ISSUE TITLE
JUnit4 tests do not run with recent snapshot m2e version

### ISSUE THREAD

**Issue by dpolivaev** [eclipse-m2e/m2e-core#353] opened 2021-10-07 11:07 UTC
I had to install the snapshot version because of an annoying bug https://github.com/eclipse-m2e/m2e-core/issues/252

Now running JUnit tests results in the following exception printed to the console:
```
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadTestLoaderClass(RemoteTestRunner.java:381)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:371)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:366)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:310)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:225)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 8 more
```
Sometimes it works after I restart eclipse for one test run but fails for the following test runs

Version numbers:

org.eclipse.m2e.feature (1.18.2.20211005-0719) "M2E Maven Integration for Eclipse Core"
org.eclipse.m2e.archetype.common (1.18.0.20211002-2123) "M2E Maven Archetype Common" [Resolved]
org.eclipse.m2e.binaryproject (1.17.4.20211002-1029) "M2E Binary Project Core" [Starting]
org.eclipse.m2e.binaryproject.ui (1.18.1.20210610-0713) "Binary project UI" [Starting]
org.eclipse.m2e.core (1.18.2.20211005-0719) "M2E Maven Integration for Eclipse Core" [Active]
org.eclipse.m2e.core.ui (1.18.2.20211002-1029) "M2E Maven Integration for Eclipse UI" [Active]
org.eclipse.m2e.discovery (1.18.1.20211002-1029) "M2E Marketplace Discovery" [Starting]
org.eclipse.m2e.editor (1.18.2.20211002-1029) "M2E Maven POM File Editor" [Starting]
org.eclipse.m2e.editor.lemminx (1.18.1.20210621-0748) "POM File editor using Wild Web Developer, Lemminx and Maven LS extension (requires Incubating components)" [Resolved]
org.eclipse.m2e.editor.xml (1.18.2.20211002-1029) "M2E Maven POM File XML Editor" [Starting]
org.eclipse.m2e.importer (1.17.3.20211002-1029) "M2E Import Framework" [Starting]
org.eclipse.m2e.jdt (1.18.2.20211002-1029) "M2E JDT Integration" [Active]
org.eclipse.m2e.jdt.ui (1.17.2.20210603-1006) "Maven Integration for Eclipse JDT UI" [Resolved]

**Comment by mickaelistria** [comment] 2021-10-07 11:09
Duplicate of #346 #347 #352 , fixed with #350. Please upgrade to newer snapshot which should have fixed it.

**Closed by mickaelistria** 2021-10-07 11:09 UTC
