### ISSUE TITLE
Bug 569907 / Parent artifacts are not resolved from Eclipse workspace

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse-m2e/m2e-core#152] opened 2021-04-01 21:32 UTC
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569907

> This is an occurrence of https://github.com/eclipse/lemminx-maven/issues/77

Use Spring Tools Suite 4.10.0 and clone the following repositories:

https://github.com/eliasbalasis/eclipse-m2e-bug-569907-root
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-tools
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-parent
https://github.com/eliasbalasis/eclipse-m2e-bug-569907-project

Then import the cloned repositories as Maven projects in the same order.

You will notice that even though the different Maven roots are detected and resolved by Eclipse the error "Non-resolvable parent POM" is still present.

**Comment by mickaelistria** [comment] 2021-04-02 08:24
Have you tried that with latest release of m2e and without STS involved ?

**Comment by eliasbalasis** [comment] 2021-04-02 12:32
Finally the problem doesn't seem to be reproducible with latest Eclipse 2021-03 (4.19.0) even though it is reproducible with latest STS 4.10.0 (built on Eclipse 4.19.0).

I guess this makes the problem STS related rather than Eclipse M2E related.

**Comment by martinlippert** [comment] 2021-04-06 15:43
I looked into this in a bit more detail and I think this is indeed an occurrence of https://github.com/eclipse/lemminx-maven/issues/77

I added my findings as a comment here (https://github.com/spring-projects/sts4/issues/617#issuecomment-814221369). This happens only if you use the Spring Tools 4 for Eclipse distribution, which comes with the Wild Web Developer components pre-installed and is caused by the XML Language Server and its Maven integration (I think). If you disable the `XML Language Server` in the preferences, the problem is gone (as a workaround).

**Comment by eliasbalasis** [comment] 2021-04-06 19:26
Thanks for the comprehensive explanation, it makes pefrect sense.

I will try disabling "XML Language Server" to verify and let you know.

**Comment by eliasbalasis** [comment] 2021-04-08 07:20
I confirm that disabling "XML Language Server" seems to be working.

However, I cannot fully trust "Spring Tool Suite 4" just yet, I will wait for the next release hoping that the bug gets fixed.

**Comment by mickaelistria** [comment] 2021-09-02 13:27
Closing as a duplicate of #287 which has more content.
A workaround at the moment is to open the files in hierarchical order (parent before children), or to just run a minimal update on the child if the parent is open after so the parent becomes visible.

**Closed by mickaelistria** 2021-09-02 13:27 UTC
